'use client';
import {useState} from 'react';
import type {QuestionVisual} from '@/lib/question-visuals';
export const adventureVisualKinds=['tenframe','ordinal','pairing','weeks','rounding','fraction-compare','composite','decimal-compare','unlike-fractions','integer-cards','rule-table','similarity','sector'];
export function AdventureVisual({v}:{v:QuestionVisual}){
 const [marked,setMarked]=useState<number[]>([]);
 function strip(n:number,d:number){return <div className="expansion-strip" role="img" aria-label={`${n} of ${d} equal parts shaded`}>{Array.from({length:d},(_,i)=><i key={i} className={i<n?'filled':''}/>)}</div>}
 if(v.kind==='tenframe')return <div className="expansion-cells">{Array.from({length:10},(_,i)=><button type="button" key={i} aria-label={`Space ${i+1}, ${i<v.a?'filled':'empty'}`} aria-pressed={marked.includes(i)} className={`expansion-cell ${i<v.a?'filled':''} ${marked.includes(i)?'marked':''}`} onClick={()=>setMarked(m=>m.includes(i)?m.filter(x=>x!==i):[...m,i])}/>)}</div>;
 if(v.kind==='ordinal')return <><p className="expansion-strip-label">Start on the left →</p><div className="expansion-row">{Array.from({length:v.a+1+v.b},(_,i)=><span key={i} className={i===v.a?'target':''}>{i===v.a?'★':'●'}</span>)}</div></>;
 if(v.kind==='pairing')return <div className="expansion-pairs">{Array.from({length:Math.ceil(v.a/2)},(_,i)=><span className="expansion-pair" key={i} aria-label={i*2+1<v.a?'A pair of counters':'One counter'}><i/>{i*2+1<v.a&&<i/>}</span>)}</div>;
 if(v.kind==='weeks')return <div className="expansion-weeks">{Array.from({length:v.a},(_,i)=><div className="expansion-week" key={i} aria-label={`Week ${i+1}, seven days`}>{['M','T','W','T','F','S','S'].map((d,j)=><i key={j}>{d}</i>)}</div>)}<div className="expansion-week" aria-label={`${v.b} extra days`}>{Array.from({length:v.b},(_,i)=><i key={i}>+</i>)}</div></div>;
 if(v.kind==='rounding')return <svg className="expansion-diagram" viewBox="0 0 400 170" role="img" aria-label={`${v.a} between ${v.b} and ${v.b+10}`}><line x1="40" y1="90" x2="360" y2="90" stroke="#769d72" strokeWidth="3"/>{Array.from({length:11},(_,i)=><g key={i}><line x1={40+32*i} y1="84" x2={40+32*i} y2="97" stroke="#769d72"/><text x={40+32*i} y="122" textAnchor="middle" fontSize="12" fill="currentColor">{v.b+i}</text></g>)}<path d={`M${40+(v.a-v.b)*32-7} 55 l7 14 l7 -14 Z`} fill="#af8436"/><text x={40+(v.a-v.b)*32} y="39" textAnchor="middle" fill="currentColor">{v.a}</text></svg>;
 if(v.kind==='fraction-compare')return <div className="expansion-fractions"><div>{strip(v.a,v.c!)}<p className="expansion-strip-label">{v.a}/{v.c}</p></div><div>{strip(v.b,v.c!)}<p className="expansion-strip-label">{v.b}/{v.c}</p></div></div>;
 if(v.kind==='unlike-fractions')return <div className="expansion-fractions"><div>{strip(1,v.a)}<p className="expansion-strip-label">1/{v.a}</p></div><div>{strip(1,v.b)}<p className="expansion-strip-label">1/{v.b}</p></div><p className="expansion-strip-label">Same-sized wholes. Different-sized pieces.</p></div>;
 if(v.kind==='composite'){const u=300/(v.a+v.b),h=v.c!*u;return <svg className="expansion-diagram" viewBox={`0 0 400 ${h+110}`} role="img" aria-label={`Adjacent rectangles ${v.a} by ${v.c} and ${v.b} by ${v.c}`}><rect x="60" y="40" width={v.a*u} height={h} fill="#bbd9a6" stroke="#739e66" strokeWidth="2"/><rect x={60+v.a*u} y="40" width={v.b*u} height={h} fill="#dec8ef" stroke="#a48ab6" strokeWidth="2"/><text x={60+v.a*u/2} y="27" textAnchor="middle" fill="currentColor">{v.a}</text><text x={60+v.a*u+v.b*u/2} y="27" textAnchor="middle" fill="currentColor">{v.b}</text><text x="36" y={45+h/2} textAnchor="middle" fill="currentColor">{v.c}</text><text x="205" y={h+79} textAnchor="middle" fill="currentColor" fontSize="13">Two parts. No overlap.</text></svg>;}
 if(v.kind==='decimal-compare'||v.kind==='integer-cards')return <div className="expansion-row">{(v.values||[v.a,v.b]).map((n,i)=><span key={i}>{n}</span>)}</div>;
 if(v.kind==='rule-table')return <table className="expansion-table"><caption>y = {v.a}x + {v.b}</caption><thead><tr><th scope="col">Input x</th><th scope="col">Output y</th></tr></thead><tbody><tr><td>0</td><td>{v.b}</td></tr><tr><td>1</td><td>{v.a+v.b}</td></tr><tr><td>{v.c}</td><td>?</td></tr></tbody></table>;
 if(v.kind==='similarity')return <svg className="expansion-diagram" viewBox="0 0 440 240" role="img" aria-label={`Similar triangles, schematic: side ${v.a} corresponds to ${v.a*v.b}; side ${v.c} corresponds to unknown`}><path d="M55 170 L100 65 L155 170 Z" fill="#d9e8bf" stroke="#789b68" strokeWidth="2"/><path d="M260 185 L320 45 L393 185 Z" fill="#e5d7f1" stroke="#9b82ad" strokeWidth="2"/><text x="63" y="110" fill="currentColor">{v.a}</text><text x="140" y="110" fill="currentColor">{v.c}</text><text x="262" y="106" fill="currentColor">{v.a*v.b}</text><text x="372" y="106" fill="currentColor">?</text><text x="220" y="229" textAnchor="middle" fontSize="13" fill="currentColor">Corresponding sides · schematic, not to scale</text></svg>;
 if(v.kind==='sector'){const theta=v.b*Math.PI/180,x=210+80*Math.cos(theta),y=112-80*Math.sin(theta);return <svg className="expansion-diagram" viewBox="0 0 420 245" role="img" aria-label={`Sector with angle ${v.b} degrees and radius ${v.a}`}><circle cx="210" cy="112" r="80" fill="#f4f0df" stroke="#d6ccb0" strokeDasharray="5 5"/><path d={`M210 112 L290 112 A80 80 0 0 0 ${x} ${y} Z`} fill="#c6dfaf" stroke="#789b68" strokeWidth="2"/><circle cx="210" cy="112" r="3" fill="#5d8350"/><text x="249" y="134" textAnchor="middle" fill="currentColor">r = {v.a}</text><text x="205" y="80" textAnchor="middle" fill="currentColor">{v.b}°</text><text x="210" y="232" textAnchor="middle" fill="currentColor" fontSize="13">What fraction of the whole-circle area?</text></svg>;}
 return null;
}
