'use client';
import {useState,type ReactNode,type CSSProperties} from 'react';
import {ArrowRight,Check,Compass,Flag,FlaskConical,Map,Medal,Play,Sparkles,Star} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {concepts,type Attempt} from '@/lib/curriculum';
import {gameStyles,supportsStyle,type DiscoveryCard,type GameStyle} from '@/lib/discovery';
import {adventureProgress,worldOf,worlds,invitation} from '@/lib/adventure-progress';
import './adventure-hub.css';

export function AdventureHub({grade,attempts,now,busy,onPlay,onAdventure,children}:{grade:number;attempts:Attempt[];now:number;busy:boolean;onPlay:(card:DiscoveryCard)=>void;onAdventure:()=>void;children:ReactNode}){
 const [tab,setTab]=useState('feed'),[world,setWorld]=useState('number'),[journeyGrade,setJourneyGrade]=useState(grade),[labStyle,setLabStyle]=useState<GameStyle>('repair'),[labQuery,setLabQuery]=useState('');
 const progress=adventureProgress(attempts,now),g=Math.min(grade,journeyGrade),classConcepts=concepts.filter(c=>c.grade===g),worldConcepts=classConcepts.filter(c=>worldOf(c)===world);
 const labConcepts=concepts.filter(c=>c.grade<=grade&&supportsStyle(c.id,labStyle)&&`${c.title} ${c.strand} class ${c.grade}`.toLowerCase().includes(labQuery.trim().toLowerCase())).sort((a,b)=>b.grade-a.grade);
 const selectedWorld=worlds.find(w=>w.id===world)!;
 return <>
  <section className="quest-banner" aria-label="A little maths adventure"><div className="quest-banner-copy"><span className="quest-overline"><Star size={15}/>A NEW WAY TO WONDER</span><h2>Big discoveries.<br/><em>Little adventures.</em></h2><p>Three puzzles. A few “what ifs”.<br/>Your next idea is waiting to be found.</p><Button onClick={onAdventure} disabled={busy}><Play size={17} fill="currentColor"/>Start a little adventure<ArrowRight size={17}/></Button><small>3 learning moments · pause anytime</small></div><div className="quest-landscape" aria-hidden="true"><span className="landscape-star star-one">✧</span><span className="landscape-star star-two">✦</span><div className="landscape-orbit"/><div className="landscape-island island-back"><span>?</span></div><div className="landscape-island island-front"><span>+ −</span><span className="landscape-sprout">✿</span></div><div className="landscape-island island-small"><span>⅓</span></div><div className="landscape-robot"><div><i/><i/></div><span/></div><span className="landscape-caption">A whole world of “aha!”</span></div></section>
  <div className="adventure-stats"><div><span className="stat-medallion"><Sparkles/></span><span><strong>{progress.sparks}</strong><small>curiosity sparks</small></span></div><div><span className="stat-medallion"><Compass/></span><span><strong>{progress.ideas}</strong><small>ideas explored</small></span></div><div><span className="stat-medallion"><Medal/></span><span><strong>{progress.badges.filter(b=>b.earned).length}<em> / 12</em></strong><small>discovery badges</small></span></div><div className="adventure-week"><span>Your little learning days</span><div>{progress.week.map(d=><span title={`${d.date}${d.active?' · explored':' · open day'}`} key={d.date} className={d.active?'day-explored':''}><b>{d.label.slice(0,1)}</b>{d.active?<Check size={14}/>:<i/>}</span>)}</div></div></div>
  <section className="daily-quests"><div className="quest-section-title"><h3><Flag size={18}/>Today’s tiny quests</h3><span>Optional invitations · India time</span></div><div className="daily-quest-grid">{progress.quests.map((q,i)=><div key={q.id} className={`daily-quest ${q.done?'quest-done':''}`}><span className="daily-quest-icon">{q.done?<Check size={20}/>:['✦','✿','▦'][i]}</span><div><strong>{q.name}</strong><p>{q.detail}</p><div className="quest-meter" role="progressbar" aria-label={q.name} aria-valuemin={0} aria-valuemax={q.target} aria-valuenow={q.progress}><i style={{width:`${100*q.progress/q.target}%`}}/></div></div><span>{q.progress}/{q.target}</span></div>)}</div></section>
  <nav className="adventure-tabs" aria-label="Explore your maths world">{[{id:'feed',label:'For you',icon:Compass},{id:'worlds',label:'My journey',icon:Map},{id:'lab',label:'Puzzle lab',icon:FlaskConical},{id:'collection',label:'My collection',icon:Medal}].map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}><t.icon size={18}/>{t.label}</button>)}</nav>
  {tab==='feed'&&children}
  {tab==='worlds'&&<section className="journey-panel"><div className="quest-section-title"><div><h3>Choose a world. Follow a trail.</h3><p>Every stop is open to explore. A leaf means you’ve tried it.</p></div><label>Class <select aria-label="Journey class" value={g} onChange={e=>setJourneyGrade(Number(e.target.value))}>{Array.from({length:grade},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div><div className="world-switcher">{worlds.map(w=>{const list=classConcepts.filter(c=>worldOf(c)===w.id);return <button key={w.id} className={`world-${w.color}`} aria-pressed={world===w.id} onClick={()=>setWorld(w.id)}><span>{w.symbol}</span><strong>{w.name}</strong><small>{list.length} stops</small></button>})}</div><div className={`journey-world world-${selectedWorld.color}`}><div className="journey-world-heading"><span>{selectedWorld.symbol}</span><h3>{selectedWorld.name}</h3><p>{selectedWorld.tagline}</p></div><div className="journey-trail">{worldConcepts.map((c,i)=>{const past=attempts.filter(a=>a.concept===c.id),connections=c.prerequisites.map(id=>concepts.find(p=>p.id===id)?.title).filter(Boolean);return <button key={c.id} disabled={busy} onClick={()=>onPlay(invitation(c))} className={`journey-stop ${past.length?'stop-explored':''}`} style={{'--stop-offset':`${[0,30,55,30,0][i%5]}px`} as CSSProperties}><span className="journey-stone">{past.length?'✿':i+1}</span><span><strong>{c.title}</strong><small>{past.length?`${past.length} learning moment${past.length===1?'':'s'} · explore again`:c.goal}</small>{connections.length>0&&<em>Connects to {connections.join(' · ')}</em>}</span><ArrowRight size={18}/></button>})}</div>{!worldConcepts.length&&<p className="world-empty">This class has no draft stops in this world yet. Choose another world or revisit an earlier class.</p>}<p className="world-note">These are exploration trails, not mastery levels. The curriculum remains an educator-review draft.</p></div></section>}
  {tab==='lab'&&<section className="puzzle-lab"><div className="quest-section-title"><div><h3>How would you like to play?</h3><p>Choose a puzzle style, then an idea. You can revisit earlier foundations.</p></div><FlaskConical size={30}/></div><div className="lab-styles" role="group" aria-label="Puzzle lab style">{gameStyles.filter(s=>s.id!=='whatif').map(s=><button key={s.id} aria-pressed={labStyle===s.id} onClick={()=>setLabStyle(s.id)}>{s.label}</button>)}</div><div className="lab-explainer"><span>{labStyle==='repair'?'⚙':labStyle==='order'?'⇢':'✧'}</span><div><strong>{labStyle==='repair'?'Rescue the mixed-up robot':labStyle==='order'?'Build a trail, tile by tile':'A fresh window into an idea'}</strong><p>{labStyle==='repair'?'Our robot made an incorrect claim. Check the maths and help it find the correct answer.':labStyle==='order'?'Compare the values, then tap the tiles from least to greatest. You can change the order before checking.':'Choose an idea below to open a fresh question in this style.'}</p></div></div><div className="lab-search"><label htmlFor="lab-search">Find an idea</label><input id="lab-search" type="search" value={labQuery} onChange={e=>setLabQuery(e.target.value)} placeholder="Try fractions, shapes or class 3…"/><span>{labConcepts.length} puzzle families</span></div><div className="lab-concepts">{labConcepts.map(c=><button disabled={busy} key={c.id} onClick={()=>onPlay(invitation(c,labStyle))}><span>Class {c.grade} · {c.strand}</span><strong>{c.title}</strong><ArrowRight size={17}/></button>)}</div>{!labConcepts.length&&<p className="world-empty">No ideas match that search in this puzzle style. Try another word or another style.</p>}</section>}
  {tab==='collection'&&<section className="collection-panel"><div className="quest-section-title"><div><h3>Little reminders of your discoveries.</h3><p>Earned from your saved learning moments. They stay when you take a break.</p></div><Medal size={30}/></div><div className="badge-grid">{progress.badges.map(b=><article className={b.earned?'badge-earned':'badge-waiting'} key={b.id}><div className="badge-medallion">{b.symbol}{b.earned&&<Check size={13}/>}</div><h4>{b.name}</h4><p>{b.detail}</p><span>{b.earned?'In your collection':`${b.progress} / ${b.target} · waiting to be discovered`}</span></article>)}</div><details className="spark-explainer"><summary>Where do curiosity sparks come from?</summary><p>Each distinct puzzle you try earns 2 sparks. A correct built, ordered or entered answer adds 3; a correct choice adds 1 instead. Sharing your thinking adds 2. Repeating the same exact puzzle does not keep adding sparks. Sparks and badges celebrate activities; they are not scores of understanding.</p><p>Daily quests refresh at midnight in India time. Your saved sparks and badges stay. Learning days count whenever you return, with no lost streak or missed-day penalty.</p></details></section>}
 </>;
}
