'use client';
import {useState} from 'react';
import {BookOpen,Blocks,Search,Download,Layers3,ShieldCheck,ExternalLink,Lightbulb,MessageCircle,Sprout,NotebookPen,Clock3,Hash,Check,Map} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {concepts,curriculumSources,gradeGuides,type Concept} from '@/lib/curriculum';

export function ConceptGuide({concept:c,onConcept,onPractice,learnerGrade}:{concept:Concept;onConcept:(id:string)=>void;onPractice:(id:string)=>void;learnerGrade?:number}){
 const source=curriculumSources[c.sourceId as keyof typeof curriculumSources];
 const related=concepts.filter(x=>x.prerequisites.includes(c.id));
 return <div className="concept-guide"><div className="guide-meta"><span className="tag tag-green">Class {c.grade}</span><span className="tag tag-neutral">{c.strand}</span><span className="tag tag-amber">Educator review pending</span></div><Tabs defaultValue="understand" key={c.id}><TabsList className="guide-tabs"><TabsTrigger value="understand">Understand</TabsTrigger><TabsTrigger value="example">Worked example</TabsTrigger><TabsTrigger value="teach">Teaching notes</TabsTrigger><TabsTrigger value="evidence">Learning evidence</TabsTrigger><TabsTrigger value="source">Source & scope</TabsTrigger></TabsList>
 <TabsContent value="understand"><div className="guide-section"><div className="eyebrow">THE CENTRAL IDEA</div><p className="guide-explanation">{c.explanation}</p><div className="goal-box"><Sprout size={21}/><div><strong>What we are working towards</strong><p>{c.goal}</p></div></div></div><div className="guide-section"><h3>Build on something familiar</h3><p>These links suggest earlier ideas to explore. They are not admission tests or ability labels.</p>{c.prerequisites.length?<div className="dependency-links">{c.prerequisites.map(id=>{const prerequisite=concepts.find(x=>x.id===id)!;return <button onClick={()=>onConcept(id)} key={id}><span>Class {prerequisite.grade}</span>{prerequisite.title}</button>})}</div>:<div className="first-foundation">Start with objects, movement and conversation. No earlier concept is assumed.</div>}</div>{related.length>0&&<div className="guide-section"><h3>Where this idea can lead</h3><div className="dependency-links">{related.map(x=><button key={x.id} onClick={()=>onConcept(x.id)}><span>Class {x.grade}</span>{x.title}</button>)}</div></div>}</TabsContent>
 <TabsContent value="example"><div className="worked-example"><div className="eyebrow">AN ORIGINAL GUIDED EXAMPLE</div><h3>{c.example.question}</h3><ol>{c.example.steps.map((step,i)=><li key={i}><span>{i+1}</span><p>{step}</p></li>)}</ol><div className="worked-answer"><span>Result</span><strong>{c.example.answer}</strong></div><p className="small-note">This example supplies the reasoning and answer. Reading it is a teaching activity, not evidence of independent understanding.</p></div><div className="guide-section"><h3>Now change the presentation</h3><p>{c.transfer}</p><p className="small-note">Invite an explanation or a drawing. A teacher can record what happened in the weekly observation.</p></div></TabsContent>
 <TabsContent value="teach"><div className="teaching-methods"><article><Blocks size={22}/><div><h3>Use objects or a diagram</h3><p>{c.objects}</p></div></article><article><MessageCircle size={22}/><div><h3>Connect it with a situation</h3><p>{c.story}</p></div></article><article><Hash size={22}/><div><h3>Connect the symbols</h3><p>After exploring the idea, work through the written example. Ask the learner to explain what each number, sign and unit represents.</p></div></article></div><div className="gentle-response"><Lightbulb size={23}/><div><div className="eyebrow">A POSSIBILITY TO EXPLORE, NOT A DIAGNOSIS</div><h3>If you notice this response…</h3><p>{c.watchFor}</p><h4>Try this next</h4><p>{c.response}</p></div></div><p className="guide-footnote">One answer can reflect wording, attention, unfamiliar context or an unclear explanation. Ask a follow-up and vary the teaching before inferring a conceptual gap.</p></TabsContent>
 <TabsContent value="evidence"><div className="understanding-prompts"><article><span>01</span><div><h3>A fresh independent attempt</h3><p>Offer a question with new values or a new arrangement. Keep the worked answer out of view and record any help given.</p></div></article><article><span>02</span><div><h3>Make the thinking visible</h3><p>Invite the learner to explain this idea through words, drawings, objects or actions. Look for: {c.goal.charAt(0).toLowerCase()+c.goal.slice(1)}</p></div></article><article><span>03</span><div><h3>Change the presentation</h3><p>{c.transfer}</p></div></article><article><span>04</span><div><h3>Return after a gap</h3><p>Try a different item after at least two days without recorded practice in this concept. Record prompting and context again.</p></div></article></div><div className="goal-box"><NotebookPen size={22}/><div><strong>A useful teacher note</strong><p>Record the question, the response, the support given and the explanation that followed. Describe the observed moment; keep the conclusion open to revision.</p></div></div><p className="guide-footnote">Two days is a prototype scheduling choice, not a scientifically established mastery threshold. No single correct answer, format count or delayed attempt establishes mastery.</p></TabsContent>
 <TabsContent value="source"><div className="source-scope"><div><span>Subject</span><strong>Mathematics</strong></div><div><span>Working reference</span><strong>{c.grade<9?'India · proposed foundation sequence':'India · CBSE 2026–27'}</strong></div><div><span>Grade placement</span><strong>{c.curriculumStatus}</strong></div><div><span>Topic location</span><strong>{c.sourceLocator}</strong></div><div><span>Content origin</span><strong>Original Aarambh explanation, example and activities</strong></div><div><span>Pedagogical approval</span><strong>Pending independent educator review</strong></div></div><a className="guide-source-link" href={source.url} target="_blank" rel="noreferrer"><BookOpen size={21}/><div><strong>{source.title}</strong><span>Reference checked {source.checked}</span></div><ExternalLink size={17}/></a><p className="guide-footnote">{source.note}</p><div className="coverage-note"><ShieldCheck size={22}/><p>A syllabus match confirms that a topic appears in the source. It does not certify these lessons, prove age suitability or grant permission to copy a textbook or train on it.</p></div></TabsContent></Tabs>
 <div className="guide-practice-footer"><div><strong>Explore the idea in practice</strong><p>Number and fraction answers are checked. Explanations still need a teacher’s interpretation.</p></div><Button onClick={()=>onPractice(c.id)} disabled={!!learnerGrade&&c.grade>learnerGrade}><BookOpen size={17}/>{learnerGrade?'Practise this concept':'Add a learner to practise'}</Button>{!!learnerGrade&&c.grade>learnerGrade&&<p className="small-note">This concept is above the active learner’s Class {learnerGrade}. You can still review the guide as an adult.</p>}</div></div>;
}

export default function CurriculumLibrary({learnerGrade,onPractice,initialConcept,onViewed}:{learnerGrade?:number;onPractice:(id:string)=>void;initialConcept?:string;onViewed?:()=>void}){
 const [grade,setGrade]=useState(String(initialConcept?concepts.find(c=>c.id===initialConcept)?.grade||1:learnerGrade||1));
 const [query,setQuery]=useState(''),[strand,setStrand]=useState('all'),[selected,setSelected]=useState<string|null>(initialConcept||null);
 const selectedConcept=concepts.find(c=>c.id===selected);
 const gradeConcepts=concepts.filter(c=>grade==='all'||c.grade===Number(grade));
 const strands=[...new Set(gradeConcepts.map(c=>c.strand))];
 const filtered=gradeConcepts.filter(c=>(strand==='all'||c.strand===strand)&&`${c.title} ${c.explanation} ${c.goal} ${c.strand}`.toLowerCase().includes(query.trim().toLowerCase()));
 const guide=grade==='all'?null:gradeGuides[Number(grade)];
 function exportCurriculum(){const blob=new Blob([JSON.stringify({version:'0.5',updated:'2026-10-07',status:'Original draft teaching content. Independent educator review pending.',sources:curriculumSources,gradeGuides,concepts},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Aarambh-Curriculum-100-Concepts.json';a.click();URL.revokeObjectURL(url);}
 function chooseGrade(value:string){setGrade(value);setStrand('all');}
 return <><div className="page-heading"><div><div className="eyebrow">CURRICULUM LIBRARY / VERSION 0.5</div><h1>Every concept has a foundation.</h1><p>Explore the idea, teach it another way, and look for evidence over time.</p></div><Button variant="outline" onClick={exportCurriculum}><Download size={17}/>Export curriculum</Button></div>
 <div className="curriculum-summary"><div><strong>{concepts.length}</strong><span>Detailed concept guides</span></div><div><strong>10</strong><span>Classes in the working map</span></div><div><strong>{concepts.length}</strong><span>Original worked examples</span></div><div><strong>4</strong><span>Ways to gather evidence</span></div></div>
 <div className="curriculum-toolbar"><div className="search-field"><Search size={19}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, explanations or learning goals…" aria-label="Search curriculum concepts"/></div><NativeSelect value={strand} onChange={e=>setStrand(e.target.value)} aria-label="Filter curriculum strand"><NativeSelectOption value="all">All maths strands</NativeSelectOption>{strands.map(s=><NativeSelectOption key={s} value={s}>{s}</NativeSelectOption>)}</NativeSelect></div>
 <div className="curriculum-classes" role="group" aria-label="Choose class"><button className={grade==='all'?'selected':''} onClick={()=>chooseGrade('all')}>All classes</button>{Array.from({length:10},(_,i)=><button key={i} className={grade===String(i+1)?'selected':''} onClick={()=>chooseGrade(String(i+1))}>Class {i+1}</button>)}</div>
 {guide&&<div className="grade-overview"><div><div className="eyebrow">CLASS {grade} / A CONNECTED SEQUENCE</div><h2>{guide.focus}</h2><p>{guide.aim}</p></div><span className={`tag ${Number(grade)<9?'tag-amber':'tag-green'}`}>{Number(grade)<9?'Grade placement under review':'2026–27 topic references'}</span></div>}
 <div className="curriculum-results"><h2>{filtered.length} concept{filtered.length===1?'':'s'} to explore</h2><span>Original teaching content · educator review pending</span></div>
 <div className="expanded-concept-grid">{filtered.map(c=><article className="expanded-concept-card" key={c.id}><div className="concept-card-header"><span className="concept-icon"><Blocks size={22}/></span><span className="tag tag-neutral">Class {c.grade} · {c.strand}</span></div><h3>{c.title}</h3><p>{c.goal}</p><div className="concept-builds"><span>BUILDS ON</span><p>{c.prerequisites.length?c.prerequisites.map(id=>concepts.find(p=>p.id===id)?.title).join(' · '):'A fresh start. No earlier concept assumed.'}</p></div><div className="concept-card-bottom"><span><NotebookPen size={14}/>Example + teaching guide</span><Button variant="outline" onClick={()=>setSelected(c.id)}>Open guide</Button></div></article>)}</div>
 {!filtered.length&&<div className="panel"><Empty><EmptyHeader><EmptyMedia variant="icon"><Search/></EmptyMedia><EmptyTitle>No concepts match these filters</EmptyTitle><EmptyDescription>Try all classes or a broader search, such as “fractions” or “equal groups”.</EmptyDescription></EmptyHeader><Button variant="outline" onClick={()=>{setQuery('');setStrand('all');setGrade('all');}}>Clear filters</Button></Empty></div>}
 <div className="curriculum-scope-panel"><Accordion type="single" collapsible><AccordionItem value="scope"><AccordionTrigger><span><ShieldCheck size={19}/>What is verified, and what still needs work?</span></AccordionTrigger><AccordionContent><div className="scope-content"><p><strong>Selected coverage, not a complete year syllabus.</strong> Each guide includes a central idea, a goal, linked foundations, a worked example, teaching approaches, a possible stumbling point and evidence prompts.</p><p>{guide?guide.next:'All classes currently have ten selected concept guides. Missing topics and edition checks are listed in each class overview.'}</p><p><strong>Classes 1–8:</strong> grade assignments are proposed and require comparison with the school’s current textbook. <strong>Classes 9–10:</strong> topic links were checked against CBSE’s 2026–27 syllabus; the right-triangle guide is prerequisite support.</p><p>All teaching content still requires independent educator review. These original drafts are available for supervised prototype testing. Imported source drafts remain separate from lessons.</p><div className="source-reference-links">{Object.values(curriculumSources).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={14}/></a>)}</div></div></AccordionContent></AccordionItem></Accordion></div>
 <Sheet open={!!selectedConcept} onOpenChange={v=>{if(!v){setSelected(null);onViewed?.();}}}><SheetContent className="curriculum-detail-sheet"><SheetHeader><div className="eyebrow">CONCEPT GUIDE</div><SheetTitle>{selectedConcept?.title}</SheetTitle><SheetDescription>{selectedConcept?.goal}</SheetDescription></SheetHeader>{selectedConcept&&<ConceptGuide concept={selectedConcept} onConcept={setSelected} onPractice={id=>{setSelected(null);onPractice(id);}} learnerGrade={learnerGrade}/>}</SheetContent></Sheet></>;
}
