'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import {Blocks,BookOpen,Check,Compass,Eye,HeartHandshake,Lightbulb,LoaderCircle,Minus,Plus,Puzzle,RefreshCw,Shapes,Shuffle,Sparkles,Speech,Sprout,X,ArrowDownUp,Bot} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {buildDiscoveryFeed,gameStyles,type DiscoveryCard,type GameStyle,type TeacherNote} from '@/lib/discovery';
import {concepts,type Attempt} from '@/lib/curriculum';
import type {Exercise} from '@/lib/lesson-engine';
import {MathVisual,AnswerCelebration} from './math-play';
import './discovery-feed.css';
import {QuestArcade} from './quest-arcade';
import {AdventureHub} from './adventure-hub';

type Learner={id:string;name:string;grade:number};
type Task=Omit<Exercise,'answer'|'hint'|'explanation'>&{id:string};
type Result={correct:boolean;assisted:boolean;interaction:string;explanation:string;answer:number};
const icons={picture:Eye,mystery:Puzzle,whatif:Sparkles,story:Speech,build:Blocks,order:ArrowDownUp,repair:Bot,balance:Blocks,estimate:Eye,target:Puzzle};
async function api<T>(payload:Record<string,unknown>):Promise<T>{const r=await fetch('/api/lesson',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||'That puzzle could not load. Please try again.');return d;}

function CardPicture({card}:{card:DiscoveryCard}){
 const c=card.concept;
 if(/fraction|decimal|ratio|percent|probability/.test(c))return <div className="card-fraction" aria-hidden="true"><div>{Array.from({length:8},(_,i)=><i className={i<3?'filled':''} key={i}/>)}</div><span>A part of something bigger</span></div>;
 if(/triangle|area|perimeter|shape|angle|circle|symmetry|volume|coordinate/.test(c))return <div className="card-geometry" aria-hidden="true"><svg viewBox="0 0 260 110"><path className="card-shape-line" d="M50 85 V20 H145 V85 Z M50 53 H145 M81 20 V85 M113 20 V85" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M180 85 L216 25 L252 85 Z" fill="currentColor" opacity=".2" stroke="currentColor" strokeWidth="3"/><text x="191" y="77" fill="currentColor" fontSize="30">?</text><text x="18" y="59" fill="currentColor" fontSize="24">?</text></svg></div>;
 if(/pattern|skip|sequence|ap10|power|exponent/.test(c))return <div className="card-pattern" aria-hidden="true"><span>2</span><span>4</span><span>6</span><span>?</span></div>;
 if(card.grade>=6||/equation|linear|algebra|polynomial/.test(c))return <div className="card-equation" aria-hidden="true"><span>x</span><b>+</b><span>3</span><b>=</b><span>?</span></div>;
 return <div className="card-counter-preview" aria-hidden="true"><div>{Array.from({length:5},(_,i)=><i key={i}/>)}</div><strong>+</strong><span>?</span></div>;
}

function GameAnswer({task,response,onResponse,locked}:{task:Task;response:string;onResponse:(s:string)=>void;locked:boolean}){
 const game=task.game;
 if(game?.kind==='dial')return <div className="number-machine"><span>YOUR NUMBER MACHINE</span><output aria-live="polite">{response||'?'}</output><input aria-label="Set your number" type="range" min={game.min} max={game.max} step={game.step} value={response||0} disabled={locked} onChange={e=>onResponse(e.target.value)}/><div><Button type="button" variant="outline" disabled={locked||Number(response||0)<=game.min!} onClick={()=>onResponse(String(Number(response||0)-1))}>− 1</Button><Button type="button" variant="outline" disabled={locked} onClick={()=>onResponse('0')}>Choose zero</Button><Button type="button" variant="outline" disabled={locked||Number(response||0)>=game.max!} onClick={()=>onResponse(String(Number(response||0)+1))}>+ 1</Button></div><p>From {game.min} to {game.max}. You control the dial.</p></div>;
 if(game?.kind==='order'){
  const chosen=response.split('').filter(Boolean).map(Number),tiles=game.tiles!;
  return <div className="order-answer"><span>Your trail · least → greatest</span><div className="order-trail" role="group" aria-label="Your ordered tiles">{Array.from({length:4},(_,i)=>chosen[i]?<button type="button" disabled={locked} key={i} aria-label={`Remove ${tiles.find(t=>t.id===chosen[i])!.label} from position ${i+1}`} onClick={()=>onResponse(chosen.filter((_,j)=>j!==i).join(''))}>{tiles.find(t=>t.id===chosen[i])!.label}</button>:<span key={i}>{i+1}</span>)}</div><div className="order-tiles" role="group" aria-label="Available tiles">{tiles.map(t=><button type="button" disabled={locked||chosen.includes(t.id)} key={t.id} onClick={()=>onResponse(response+t.id)}>{t.label}</button>)}</div><p>Tap a tile to add it. Tap a tile in your trail to remove it.</p></div>;
 }
 if(game?.kind==='choice')return <fieldset className="game-choice"><legend>Which answer fits?</legend><div>{game.options!.map((option,i)=><button type="button" key={option} onClick={()=>onResponse(option)} disabled={locked} aria-pressed={response===option}><span>{String.fromCharCode(65+i)}</span><strong>{option}</strong>{response===option&&<Check size={20}/>}</button>)}</div></fieldset>;
 if(game?.kind==='shade'){
  const n=response?Number(response.split('/')[0]):0;
  return <div className="shade-answer"><strong>Make your fraction</strong><div className="shade-answer-parts" role="group" aria-label="Shade your fraction answer">{Array.from({length:game.parts!},(_,i)=><button key={i} type="button" disabled={locked} aria-label={`Shade the first ${i+1} of ${game.parts} equal parts`} aria-pressed={i<n} className={i<n?'selected':''} onClick={()=>onResponse(`${i+1}/${game.parts}`)}/>)}</div><div><Button type="button" variant="outline" disabled={locked} onClick={()=>onResponse(`0/${game.parts}`)}>Clear strip</Button><output aria-live="polite">{response||'No fraction chosen yet'}</output></div><p>Tap a part to shade up to that point. Tap an earlier part to use fewer.</p></div>;
 }
 if(game?.kind==='build'){
  const n=Number(response||0);
  return <div className="build-answer"><div className="build-controls"><button type="button" disabled={locked||n===0} onClick={()=>onResponse(String(n-1))} aria-label="Remove one counter"><Minus/></button><output aria-live="polite">{n}</output><button type="button" disabled={locked||n===game.limit} onClick={()=>onResponse(String(n+1))} aria-label="Add one counter"><Plus/></button></div><div className="answer-counter-tray" aria-label={`${n} counters in your answer`}>{n?Array.from({length:n},(_,i)=><span key={i}/>):<span className="empty-answer-tray">An empty tray. You can choose zero, too.</span>}</div><div className="build-shortcuts"><Button type="button" variant="outline" disabled={locked||n+5>game.limit!} onClick={()=>onResponse(String(n+5))}>Add 5</Button><Button type="button" variant="outline" disabled={locked} onClick={()=>onResponse('0')}>Choose 0</Button></div></div>;
 }
 return <label className="game-number-answer">Your answer<div><Input value={response} autoComplete="off" inputMode="text" onChange={e=>onResponse(e.target.value)} disabled={locked} placeholder="Number or fraction, e.g. 1/2" aria-label="Your puzzle answer"/>{task.unit&&<span>{task.unit}</span>}</div></label>;
}

export default function DiscoveryFeed({learner,learners,attempts,feedback,loading,onSelect,onAddLearner,onSaved,onTeacher,onWorkspace}:{learner?:Learner;learners:Learner[];attempts:Attempt[];feedback:TeacherNote[];loading:boolean;onSelect:(id:string)=>void;onAddLearner:(grade?:number)=>void;onSaved:()=>Promise<unknown>;onTeacher:()=>void;onWorkspace:()=>void}){
 const [shuffle,setShuffle]=useState(0),[filter,setFilter]=useState<GameStyle|'all'>('all'),[previewGrade,setPreviewGrade]=useState('1'),[now,setNow]=useState(()=>Date.now());
 const [selected,setSelected]=useState<DiscoveryCard|null>(null),[task,setTask]=useState<Task|null>(null),[response,setResponse]=useState(''),[hint,setHint]=useState(''),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedNote,setFeedNote]=useState('');
 const [adventure,setAdventure]=useState(false),[rounds,setRounds]=useState<{id:string;concept:string;correct:boolean}[]>([]),[thinking,setThinking]=useState(''),[thinkingSaved,setThinkingSaved]=useState(false);
 const [mission,setMission]=useState<{cards:DiscoveryCard[];name:string}|null>(null);
 const operation=useRef(0),inFlight=useRef(false);useEffect(()=>()=>{operation.current++;},[]);
 const cards=useMemo(()=>buildDiscoveryFeed(learner?.grade||Number(previewGrade),attempts,feedback,now,shuffle),[learner?.grade,previewGrade,attempts,feedback,now,shuffle]);
 const visible=filter==='all'?cards:cards.filter(c=>c.style===filter),first=cards[0];
 const explored=[...new Set(attempts.map(a=>a.concept))],themeCount=new Set(concepts.filter(c=>explored.includes(c.id)).map(c=>c.strand)).size;
 const nextCard=cards.find(c=>c.reasonCode==='foundation')||first;
 async function play(card:DiscoveryCard,continuing=false){
  if(!learner){onAddLearner(Number(previewGrade));return;}if(inFlight.current)return;
  if(!continuing){setAdventure(false);setRounds([]);setMission(null);}setThinking('');setThinkingSaved(false);
  const token=++operation.current;inFlight.current=true;setSelected(card);setTask(null);setResult(null);setHint('');setResponse('');setError('');setBusy(true);
  try{const q=await api<Task>({action:'start',learner:learner.id,concept:card.concept,game:card.style});if(token===operation.current)setTask(q);}catch(e){if(token===operation.current)setError((e as Error).message);}finally{if(token===operation.current){setBusy(false);inFlight.current=false;}}
 }
 function close(){operation.current++;inFlight.current=false;setSelected(null);setTask(null);setResult(null);setBusy(false);setError('');setAdventure(false);setRounds([]);}
 async function submit(e:FormEvent){e.preventDefault();if(!task||!response||inFlight.current||result)return;const token=operation.current;inFlight.current=true;setBusy(true);setError('');
  try{const r=await api<Result>({action:'answer',task:task.id,response});if(token===operation.current){setResult(r);if(adventure)setRounds(old=>old.some(x=>x.id===task.id)?old:[...old,{id:task.id,concept:task.concept,correct:r.correct}]);setNow(Date.now());setFeedNote('Your next invitations have changed with this learning moment.');}try{await onSaved();}catch{if(token===operation.current)setError('Your answer was saved. Reload the page to refresh your discovery cards.');}}catch(e){if(token===operation.current)setError((e as Error).message);}finally{if(token===operation.current){setBusy(false);inFlight.current=false;}}
 }
 async function help(){if(!task||inFlight.current)return;const token=operation.current;inFlight.current=true;setBusy(true);setError('');try{const r=await api<{hint:string}>({action:'hint',task:task.id});if(token===operation.current)setHint(r.hint);}catch(e){if(token===operation.current)setError((e as Error).message);}finally{if(token===operation.current){setBusy(false);inFlight.current=false;}}}
 async function saveThinking(){if(!task||!thinking.trim()||inFlight.current)return;const token=operation.current;inFlight.current=true;setBusy(true);setError('');try{await api({action:'reflect',task:task.id,reflection:thinking});if(token===operation.current)setThinkingSaved(true);await onSaved();}catch(e){if(token===operation.current)setError((e as Error).message);}finally{if(token===operation.current){setBusy(false);inFlight.current=false;}}}
 function startPack(cards:DiscoveryCard[],name:string){if(!learner){onAddLearner(Number(previewGrade));return;}if(inFlight.current)return;setMission({cards,name});setAdventure(true);setRounds([]);void play(cards[0],true);}
 function startAdventure(){setMission(null);if(!learner){onAddLearner(Number(previewGrade));return;}if(inFlight.current)return;setAdventure(true);setRounds([]);void play(first,true);}
 function addLearner(){onAddLearner(learner?learner.grade:Number(previewGrade));}
 function newDeck(){setShuffle(s=>s+1);setNow(Date.now());setFeedNote('A different mix, with your learning history kept in mind.');}
 return <div className="discovery-home">
  <div className="discovery-heading"><div><div className="discovery-kicker"><Compass size={16}/>YOUR LITTLE WORLD OF MATHS</div><h1>{learner?`Hey ${learner.name}, what makes you curious?`:'A little puzzle. A big “aha!”'}</h1><p>Pick something that catches your eye. Let’s figure it out together.</p></div><div className="discovery-profile">{learner?<><span className="discovery-avatar">{learner.name[0].toUpperCase()}</span><label><span>Learning space</span><NativeSelect aria-label="Choose learner for discovery feed" value={learner.id} onChange={e=>onSelect(e.target.value)}>{learners.map(l=><NativeSelectOption value={l.id} key={l.id}>{l.name} · Class {l.grade}</NativeSelectOption>)}</NativeSelect></label><Button variant="ghost" size="icon" aria-label="Add another learner" onClick={addLearner}><Plus size={18}/></Button></>:<><label><span>Explore a class</span><NativeSelect aria-label="Preview class" value={previewGrade} onChange={e=>setPreviewGrade(e.target.value)}>{Array.from({length:10},(_,i)=><NativeSelectOption value={i+1} key={i}>Class {i+1}</NativeSelectOption>)}</NativeSelect></label><Button onClick={addLearner} disabled={loading}>Make my space</Button></>}</div></div>
  <AdventureHub key={learner?.id||previewGrade} grade={learner?.grade||Number(previewGrade)} attempts={attempts} now={now} busy={busy||loading} onPlay={play} onAdventure={startAdventure}>
  <QuestArcade grade={learner?.grade||Number(previewGrade)} attempts={attempts} now={now} busy={busy||loading} onPack={startPack}/><div className="discovery-filters"><div role="group" aria-label="Filter discovery cards"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}><Compass size={16}/>For you</button>{gameStyles.map(s=>{const Icon=icons[s.id];return <button key={s.id} aria-pressed={filter===s.id} onClick={()=>setFilter(s.id)}><Icon size={16}/>{s.label}</button>})}</div><button className="shuffle-deck" onClick={newDeck} disabled={busy}><Shuffle size={16}/>Mix the cards</button></div>
  <p className="feed-update" role="status">{feedNote||'No timer. No race. Follow your curiosity.'}</p>
  {loading?<div className="discovery-loading"><LoaderCircle className="spin"/>Getting your puzzle cards ready…</div>:<div className="discovery-grid">{visible.map((card,i)=>{const Icon=icons[card.style],style=gameStyles.find(s=>s.id===card.style)!;return <article key={card.id} className={`discovery-card palette-${i%6} ${i===0&&filter==='all'?'discovery-featured':''}`} style={{'--card-delay':`${Math.min(i*45,250)}ms`} as CSSProperties}>
   <div className="discovery-card-top"><span><Icon size={16}/>{style.label}</span>{card.reasonCode==='teacher'?<span className="card-tiny-tag">Teacher’s pick</span>:card.reasonCode==='revisit'?<span className="card-tiny-tag">Hello again</span>:i===0?<span className="card-tiny-tag">A little invitation</span>:<span className="card-number">{String(i+1).padStart(2,'0')}</span>}</div>
   <CardPicture card={card}/><div className="discovery-card-copy"><h2>{card.hook}</h2><p>{card.title}</p></div><div className="discovery-card-bottom"><span>{card.strand}</span><Button onClick={()=>play(card)} disabled={busy}>{style.action}<Icon size={16}/></Button></div><details className="card-why"><summary>Why this card?</summary><p>{card.reason}</p></details>
  </article>})}</div>}
  {!loading&&!visible.length&&<div className="empty-deck"><Puzzle size={28}/><h2>A different kind of puzzle?</h2><p>There isn’t one in this mix yet. Shuffle the deck or see all your invitations.</p><div><Button onClick={newDeck}>Mix the cards</Button><Button variant="outline" onClick={()=>setFilter('all')}>See all cards</Button></div></div>}
  </AdventureHub>
  <div className="discovery-bottom"><div><HeartHandshake size={23}/><div><strong>A companion, not a competition.</strong><p>There’s always another way to try. You can pause whenever you like.</p></div></div><div><Button variant="outline" onClick={onTeacher}>Teacher desk</Button><Button variant="ghost" onClick={onWorkspace}>Workspace overview</Button></div></div>
  <details className="feed-adaptation"><summary><Lightbulb size={16}/>For adults: how these invitations change</summary><p>Suggestions use saved answers, support given, linked prerequisites and teacher priorities. After a difficult moment we vary the explanation; repeated difficulty can offer an earlier idea. Several distinct, unassisted answers across formats can suggest a connected concept within the selected class boundary. Previously explored ideas can return after a gap.</p><p>Choosing from supplied answers is exploratory practice. It is not counted as an independent constructed answer. Sparks, quests, learning days and badges celebrate activities. They do not change recommendation thresholds or measure mastery. Optional explanations are saved for teacher review; they are not automatically assessed. New histories are empty. The initial class selection sets a curriculum boundary, not an ability judgment.</p><p>This prototype uses recommendation rules, not a model that retrains itself or diagnoses understanding. Teacher notes guide the feed through their selected concept and approach; free-text observations remain context for an educator. The curriculum and recommendation thresholds still need educator validation.</p></details>
  <Dialog open={!!selected} onOpenChange={open=>{if(!open)close();}}><DialogContent className={`puzzle-dialog puzzle-${selected?.style||'picture'}`}><DialogHeader><div className="puzzle-eyebrow"><Sparkles size={15}/>{gameStyles.find(s=>s.id===selected?.style)?.label||'A little discovery'}</div><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>Try an idea. Make an answer. There’s room to change your thinking.</DialogDescription></DialogHeader>
   {adventure&&<div className="adventure-checkpoints" aria-label={`${rounds.length} of 3 learning moments saved`}>{[0,1,2].map(i=><span className={rounds.length>i?'checkpoint-done':''} key={i}>{rounds.length>i?<Check size={14}/>:i+1}</span>)}<strong>{mission?.name||'Your little adventure'}</strong></div>}
   {!task&&busy&&<div className="puzzle-loading"><LoaderCircle className="spin" size={28}/><p>A fresh puzzle is on its way…</p></div>}
   {error&&<div className="puzzle-error" role="alert">{error}{!task&&selected&&<Button variant="outline" onClick={()=>play(selected,adventure)} disabled={busy}>Try loading again</Button>}</div>}
   {task&&<div key={task.id} className="puzzle-round"><div className="puzzle-question"><span>{task.review?'Let’s revisit an idea':'Your next little challenge'}</span><h2>{task.prompt}</h2></div>{task.visual&&<MathVisual key={task.id} visual={task.visual} concept={task.concept}/>}
    {!result&&<form onSubmit={submit}><GameAnswer task={task} response={response} onResponse={setResponse} locked={busy}/><p className="game-input-note">{task.game?.instruction}</p><div className="puzzle-actions"><Button type="submit" disabled={busy||!response.trim()||(task.game?.kind==='order'&&response.length!==4)}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Try my answer</Button><Button type="button" variant="outline" disabled={busy||!!hint} onClick={help}><Lightbulb size={17}/>Give me a clue</Button></div></form>}
    {hint&&<div className="game-hint" role="status"><Lightbulb size={18}/><p>{hint}</p></div>}
    {result&&<div className={`puzzle-result ${result.correct?'puzzle-match':'puzzle-rethink'}`} role="status">{result.correct&&<AnswerCelebration/>}<h3>{result.correct?'That fits. You found a way!':'Let’s find another way together.'}</h3><p>{result.explanation}</p><span>{result.interaction==='choice'?'You explored by choosing. Next, try making an answer yourself.':result.assisted?'A clue helped this time. That’s part of exploring.':'This is one learning moment. We’ll explore the idea in more ways.'}</span>{!result.correct&&<p className="puzzle-teaching-note">{concepts.find(c=>c.id===task.concept)?.response}</p>}<div className="thinking-note"><label htmlFor="puzzle-thinking">How did you work it out? <span>(optional)</span></label><textarea id="puzzle-thinking" value={thinking} maxLength={1200} disabled={busy} onChange={e=>{setThinking(e.target.value);setThinkingSaved(false);}} placeholder="I noticed… I grouped… I drew…"/><Button variant="outline" disabled={busy||!thinking.trim()||thinkingSaved} onClick={saveThinking}>Save my thinking</Button>{thinkingSaved&&<span className="thinking-saved"><Check size={14}/>Saved for your teacher</span>}<p>You can also show your teacher with objects or a drawing. This note isn’t scored by the companion.</p></div>
     {adventure&&rounds.length>=3&&<div className="adventure-finish"><span>✿</span><h3>Three moments. A little more wonder.</h3><p>You explored {new Set(rounds.map(r=>r.concept)).size} idea{new Set(rounds.map(r=>r.concept)).size===1?'':'s'} and saved three learning moments. Your next invitations will grow from these. This is a lovely place to pause.</p></div>}
     <div className="puzzle-result-actions">{(!adventure||rounds.length<3)&&<Button onClick={()=>play(mission&&result.correct?mission.cards[rounds.length]||first:result.correct?first:nextCard,adventure)} disabled={busy}><Sparkles size={17}/>{adventure?`Next discovery · ${rounds.length+1} of 3`:result.correct?'What shall we explore next?':'Try another way'}</Button>}<Button variant="outline" onClick={close}>{adventure&&rounds.length>=3?'Finish my adventure':adventure?'Pause & keep my discoveries':'Back to my cards'}</Button></div></div>}
    <p className="puzzle-reassurance"><HeartHandshake size={15}/>No timer. Take the time you need.</p>
   </div>}
  </DialogContent></Dialog>
 </div>;
}
