'use client';

import {useEffect,useState,type CSSProperties,type ReactNode} from 'react';
import {Blocks,Check,Grid2X2,Hand,Lightbulb,Pause,Play,RotateCcw,Sparkles} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AdventureVisual,adventureVisualKinds} from './adventure-visuals';
import './adventure-hub.css';
import type {QuestionVisual} from '@/lib/question-visuals';

const delay=(i:number)=>({'--item-delay':`${Math.min(i*35,700)}ms`} as CSSProperties);
const clockTime=(n:number)=>`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;
function Canvas({label,children}:{label:string;children:ReactNode}){return <svg className="math-canvas" viewBox="0 0 480 260" role="img" aria-label={label}>{children}</svg>}
function ClockFace({minutes,label}:{minutes:number;label:string}){
 const point=(deg:number,r:number)=>[90+Math.sin(deg*Math.PI/180)*r,90-Math.cos(deg*Math.PI/180)*r];
 const m=point(minutes%60*6,58),h=point((minutes%720)/2,38);
 return <div className="clock-card"><span>{label}</span><svg viewBox="0 0 180 180" role="img" aria-label={`${label}: ${clockTime(minutes)}`}><circle cx="90" cy="90" r="83" fill="white" stroke="#bad0db" strokeWidth="3"/>{Array.from({length:12},(_,i)=>{const [x,y]=point((i+1)*30,67);return <text key={i} x={x} y={y+5} textAnchor="middle" fontSize="14">{i+1}</text>})}<line className="draw-line" x1="90" y1="90" x2={h[0]} y2={h[1]} stroke="#204e43" strokeWidth="7" strokeLinecap="round"/><line className="draw-line" x1="90" y1="90" x2={m[0]} y2={m[1]} stroke="#337abb" strokeWidth="4" strokeLinecap="round"/><circle cx="90" cy="90" r="5" fill="#204e43"/></svg><strong>{clockTime(minutes)}</strong></div>
}

export function MathVisual({visual:v,concept=''}:{visual:QuestionVisual;concept?:string}){
 const [marked,setMarked]=useState<number[]>([]),[grid,setGrid]=useState(false),[turn,setTurn]=useState(0),[replay,setReplay]=useState(0),[position,setPosition]=useState(v.a);
 const tap=(i:number)=>setMarked(m=>m.includes(i)?m.filter(n=>n!==i):[...m,i]);
 const reset=()=>{setMarked([]);setGrid(false);setTurn(0);setPosition(v.a);setReplay(n=>n+1);};
 function counter(i:number,blue=false,crossed=false){return <button type="button" key={i} style={delay(i)} className={`play-counter visual-item ${blue?'is-blue':''} ${crossed?'is-crossed':''} ${marked.includes(i)?'is-marked':''}`} aria-label={`${blue?'Blue':'Green'} counter ${i+1}${crossed?', crossed out':''}`} aria-pressed={marked.includes(i)} onClick={()=>tap(i)}>{marked.includes(i)&&<Check size={17}/>}</button>}
 function strip(n:number,d:number,start=0,label?:string){return <div className="strip-row"><div className="strip-track" role="group" aria-label={`${n} of ${d} equal parts shaded`}>{Array.from({length:d},(_,i)=><button type="button" aria-label={`Part ${i+1}, ${i<n?'shaded':'unshaded'}`} aria-pressed={marked.includes(i+start)} onClick={()=>tap(i+start)} key={i} style={delay(i)} className={`strip-part visual-item ${i<n?'is-filled':''} ${marked.includes(i+start)?'is-marked':''}`}/>)}</div>{label&&<span>{label}</span>}</div>}
 let content:ReactNode=null,instruction='Look closely at the model. Use the information to work out your answer.',title='See the maths';
 if(adventureVisualKinds.includes(v.kind)){title='A different way to see it';instruction=v.kind==='tenframe'?'Tap spaces to mark them as you count. The filled part stays the same.':'Look at the given quantities and their relationships. Use them to construct your answer.';content=<AdventureVisual key={replay} v={v}/>;}else if(['counters','subtract','compare'].includes(v.kind)){
  const compare=v.kind==='compare';title=compare?'Compare the collections':v.kind==='subtract'?'What stays behind?':'Tap. Count. Discover.';
  instruction='Tap each counter to mark it as you count. Tap again to unmark it.';
  content=<div className="counter-collections"><div className="counter-tray">{Array.from({length:v.a},(_,i)=>counter(i,false,v.kind==='subtract'&&i>=v.a-v.b))}</div>{v.kind!=='subtract'&&v.b>0&&<><span className="collection-sign">{compare?'or':concept==='probability'?'&':'+'}</span><div className="counter-tray blue-tray">{Array.from({length:v.b},(_,i)=>counter(v.a+i,true))}</div></>}</div>;
 }else if(v.kind==='groups'){
  title='Equal groups, one idea';instruction='Tap the counters as you count. Each tray holds an equal group.';
  content=<div className="group-trays">{Array.from({length:v.a},(_,i)=><div key={i} className="group-tray"><span>Group {i+1}</span><div>{Array.from({length:v.b},(_,j)=>counter(i*v.b+j,i%2===1))}</div></div>)}</div>;
 }else if(v.kind==='fraction'||v.kind==='fraction-sum'){
  title='A whole, in equal parts';instruction='The coloured parts belong to the same-sized whole. Tap any part to outline it.';
  content=<div className="fraction-model">{v.kind==='fraction'?strip(v.a,v.b):<>{strip(v.a,v.c!,0,v.labels?.[0])}<span className="collection-sign">+</span>{strip(v.b,v.c!,100,v.labels?.[1])}</>}<span className="whole-label">Each complete strip represents one whole</span></div>;
 }else if(v.kind==='place'){
  title='Tens you can see';instruction='Each long rod contains ten small squares. The single counters are ones.';
  content=<div className="base-ten-model"><div><div className="rod-collection">{Array.from({length:v.a},(_,i)=><div className="play-rod visual-item" style={delay(i)} key={i}>{Array.from({length:10},(_,j)=><i key={j}/>)}</div>)}</div><span>Tens</span></div><div><div className="counter-tray">{Array.from({length:v.b},(_,i)=>counter(i,true))}</div><span>Ones</span></div></div>;
 }else if(v.kind==='rectangle'||v.kind==='square-root'||v.kind==='symmetry'){
  const root=v.kind==='square-root',sym=v.kind==='symmetry';title=sym?'Turn it. Compare it.':root?'A square made of squares':'Explore the shape';
  instruction=sym?'Rotate the inner shape a quarter turn. Does it match the fixed dotted outline?':'Show the grid to see equal unit squares. The labelled lengths stay the same.';
  const unit=160/Math.max(v.a,v.b),w=v.a*unit,h=v.b*unit,x=240-w/2,y=125-h/2;
  content=<><Canvas label={sym?`${v.a===v.b?'Square':'Non-square rectangle'} with a fixed outline`:root?`Square of area ${v.a*v.b}, unknown side length`:`Rectangle, ${v.a} by ${v.b} cm`}>
   {sym&&<rect x={x} y={y} width={w} height={h} fill="none" stroke="#7897ad" strokeWidth="3" strokeDasharray="5 5"/>}
   <g className="turn-shape" style={{transformOrigin:'240px 125px',transform:`rotate(${turn*90}deg)`}}><rect x={x} y={y} width={w} height={h} rx="2" fill="#c9eccb" fillOpacity={sym ? 0.65 : 1} stroke="#28714e" strokeWidth="3"/>{grid&&Array.from({length:v.a-1},(_,i)=><line className="draw-line" key={`v${i}`} x1={x+(i+1)*unit} y1={y} x2={x+(i+1)*unit} y2={y+h} stroke="#6ba77c"/>)}{grid&&Array.from({length:v.b-1},(_,i)=><line className="draw-line" key={`h${i}`} x1={x} y1={y+(i+1)*unit} x2={x+w} y2={y+(i+1)*unit} stroke="#6ba77c"/>)}</g>
   {!sym&&<><text x="240" y={y-17} textAnchor="middle">{root?'?':`${v.a} cm`}</text><text x={x+w+15} y="130">{root?'?':`${v.b} cm`}</text>{root&&<text x="240" y="240" textAnchor="middle">Area = {v.a*v.b} square units</text>}</>}
  </Canvas><div className="model-tools">{sym?<Button variant="outline" onClick={()=>setTurn(t=>t+1)}><RotateCcw size={16}/>Rotate 90°</Button>:<Button variant="outline" aria-pressed={grid} onClick={()=>setGrid(g=>!g)}><Grid2X2 size={16}/>{grid?'Hide unit grid':'Show unit grid'}</Button>}</div></>;
 }else if(v.kind==='reflection'){
  title='Test a mirror line';instruction='Choose a line. The purple outline is the reflected shape. Does it match the green original?';
  const w=v.a*27,h=v.b*27,theta=turn%4===0?Math.PI/2:turn%4===1?0:turn%4===2?Math.atan(h/w):-Math.atan(h/w),co=Math.cos(2*theta),si=Math.sin(2*theta);
  content=<><Canvas label={`${v.a===v.b?'Square':'Non-square rectangle'} and its reflection in the selected line`}><g transform="translate(240 125)"><rect x={-w/2} y={-h/2} width={w} height={h} fill="#c9e5cf" stroke="#438160" strokeWidth="2"/><g transform={`matrix(${co} ${si} ${si} ${-co} 0 0)`}><rect x={-w/2} y={-h/2} width={w} height={h} fill="none" stroke="#8863b4" strokeWidth="4" strokeDasharray="7 4"/></g><line x1={-110*Math.cos(theta)} y1={-110*Math.sin(theta)} x2={110*Math.cos(theta)} y2={110*Math.sin(theta)} stroke="#cf8540" strokeWidth="3"/></g></Canvas><div className="reflection-tools" role="group" aria-label="Select a mirror line">{['Vertical','Horizontal','Diagonal 1','Diagonal 2'].map((label,i)=><button key={label} aria-pressed={turn%4===i} onClick={()=>setTurn(i)}>{label}</button>)}</div></>;
 }else if(v.kind==='triangle'){
  title=v.c?'Find the relationship':'Three sides, one connection';const h=145,w=h*v.b/v.a,x=100,y=40,bottom=y+h;
  content=<Canvas label={`Right triangle. Vertical side ${v.a}, base ${v.b}, hypotenuse ${v.c||'unknown'}`}><path className="draw-line" d={`M${x} ${y} V${bottom} H${x+w} Z`} fill="#deedff" stroke="#407ead" strokeWidth="3"/><path d={`M${x} ${bottom-18} h18 v18`} fill="none" stroke="#407ead" strokeWidth="2"/><text x={x-17} y={y+h/2} textAnchor="end">{v.a}</text><text x={x+w/2} y={bottom+30} textAnchor="middle">{v.b}</text><text x={x+w/2+20} y={y+h/2-12}>{v.c||'?'}</text>{v.c&&<text x={x+w-47} y={bottom-12}>θ</text>}<text x="240" y="247" textAnchor="middle">{v.c?'θ faces the vertical side':'Find the missing side'}</text></Canvas>;
 }else if(v.kind==='numberline'){
  const denominator=v.c||1,min=Math.min(v.a,0)-denominator,max=Math.max(v.a+v.b,0)+denominator,range=max-min;
  const label=(n:number)=>denominator===1?String(n):n===0?'0':`${n}/${denominator}`;
  title='Take a walk on the number line';instruction=`Start at ${label(v.a)}. Move ${v.b} steps right; each step is ${denominator===1?'1':`1/${denominator}`}. Move the marker to your choice.`;
  content=<div className="numberline-model"><Canvas label={`Number line from ${label(min)} to ${label(max)}. Starting point ${label(v.a)}.`}><line x1="30" y1="135" x2="450" y2="135" stroke="#617e91" strokeWidth="3"/>{Array.from({length:range+1},(_,i)=>{const n=min+i,x=30+420*i/range;return <g key={n}><line x1={x} y1="128" x2={x} y2="145" stroke="#617e91"/><text x={x} y="166" textAnchor="middle" fontSize="13">{denominator===1||n%denominator===0?label(n):''}</text></g>})}<circle cx={30+420*(v.a-min)/range} cy="135" r="8" fill="none" stroke="#337abb" strokeWidth="3"/><g className="number-marker" style={{transform:`translateX(${30+420*(position-min)/range}px)`}}><path d="M-9 99 L0 116 L9 99 Z" fill="#246044"/><text x="0" y="86" textAnchor="middle">{label(position)}</text></g></Canvas><label className="marker-slider">Move your marker<input type="range" min={min} max={max} step="1" value={position} onChange={e=>setPosition(Number(e.target.value))} aria-label="Number line marker" aria-valuetext={label(position)}/></label></div>;
 }else if(v.kind==='clocks'){
  title='From one moment to another';content=<div className="clock-pair"><ClockFace minutes={v.a} label="Start"/><span className="clock-gap">…</span><ClockFace minutes={v.b} label="Finish"/></div>;instruction='The short hand shows hours. The long hand shows minutes. Count the time between the two clocks.';
 }else if(v.kind==='ruler'){
  title='Measure the gap';const max=v.b+2,scale=410/max;content=<Canvas label={`Strip begins at ${v.a} cm and ends at ${v.b} cm on a ruler`}><rect x="30" y="125" width="410" height="58" rx="5" fill="#ffedb9" stroke="#b9a675"/>{Array.from({length:max+1},(_,i)=><g key={i}><line x1={30+i*scale} y1="125" x2={30+i*scale} y2="143" stroke="#746345"/><text x={30+i*scale} y="165" textAnchor="middle" fontSize="14">{i}</text></g>)}<rect className="draw-line" x={30+v.a*scale} y="81" width={(v.b-v.a)*scale} height="23" rx="5" fill="#81b5e8"/><text x="240" y="216" textAnchor="middle">Ruler markings in centimetres</text></Canvas>;
 }else if(v.kind==='bars'){
  title='Read the picture';const values=v.values!,max=Math.max(...values);content=<div className="bar-model">{values.map((n,i)=><div className="bar-model-row" key={i}><span>{v.labels?.[i]}</span><div><div className="diagram-bar" style={{width:`${n/max*100}%`,...delay(i)}}><strong>{n}</strong></div></div></div>)}<span className="whole-label">Same scale · {v.labels?.at(-1)}</span></div>;
 }else if(v.kind==='digits'||v.kind==='sequence'||v.kind==='outcomes'){
  title=v.kind==='digits'?'Every position has a value':v.kind==='outcomes'?'Six equally likely outcomes':'Notice what changes';
  const values=v.kind==='outcomes'?[1,2,3,4,5,6]:v.values!;
  instruction=v.kind==='outcomes'?'Tap the outcomes you want to consider. Each of the six outcomes has the same chance.':v.kind==='digits'?'Read the place label below each digit.':'Tap a card to mark it while you explore the pattern.';
  content=<><div className="number-tiles">{values.map((n,i)=><button type="button" className={`number-tile visual-item ${marked.includes(i)?'is-marked':''}`} style={delay(i)} key={i} onClick={()=>tap(i)} aria-pressed={marked.includes(i)}><strong>{n}</strong>{v.kind==='digits'&&<span>{v.labels?.[i]}</span>}</button>)}{v.kind==='sequence'&&concept!=='statistics9'&&<span className="missing-tile">?</span>}</div>{v.kind==='sequence'&&v.labels&&<span className="whole-label">{v.labels[0]}</span>}</>;
 }else if(v.kind==='polygon'){
  title='Follow the boundary';content=<Canvas label={v.a===3?'Triangle with three straight edges':'Rectangle with four straight edges'}><path className="draw-line" d={v.a===3?'M240 38 L365 210 H115 Z':'M115 60 H365 V200 H115 Z'} stroke="#377dac" strokeWidth="5" fill="#d8ecfb"/></Canvas>;
 }else if(v.kind==='pictograph'){
  title='A picture with a key';content=<><div className="pictograph">{Array.from({length:v.a},(_,i)=><Blocks className="visual-item" style={delay(i)} size={38} key={i}/>)}</div><div className="picture-key"><Blocks size={20}/><span>Each symbol represents {v.b} books</span></div></>;
 }else if(v.kind==='circle'){
  title='From the centre to the edge';content=<Canvas label={`Circle with radius ${v.a} cm`}><circle className="draw-line" cx="240" cy="120" r="85" fill="#e4ddff" stroke="#7964b0" strokeWidth="3"/><line x1="240" y1="120" x2="325" y2="120" stroke="#6c55a4" strokeWidth="3"/><circle cx="240" cy="120" r="4" fill="#6c55a4"/><text x="280" y="105" textAnchor="middle">{v.a} cm</text><text x="240" y="245" textAnchor="middle">Radius · centre to boundary</text></Canvas>;
 }else if(v.kind==='angle'||v.kind==='turn'){
  const theta=v.a*Math.PI/180,endX=220+110*Math.cos(theta),endY=170-110*Math.sin(theta);title=v.kind==='angle'?'Angles that fit together':'Follow the turn';
  content=<Canvas label={v.kind==='angle'?`Straight line divided into ${v.a} degrees and an unknown angle`:`${v.a===90?'Quarter':'Half'} turn`}><line x1={v.kind==='angle'?85:220} y1="170" x2="360" y2="170" stroke="#6a7f91" strokeWidth="3"/><line className="draw-line" x1="220" y1="170" x2={endX} y2={endY} stroke="#397baf" strokeWidth="4"/><path className="draw-line" d={`M275 170 A55 55 0 0 0 ${220+55*Math.cos(theta)} ${170-55*Math.sin(theta)}`} fill="none" stroke="#cd9450" strokeWidth="5"/><circle cx="220" cy="170" r="5" fill="#397baf"/><text x="240" y="225" textAnchor="middle">{v.kind==='angle'?`${v.a}° shown · find the other angle`:v.a===90?'Quarter turn':'Half turn'}</text></Canvas>;
 }else if(v.kind==='balance'){
  title='Keep both sides equal';content=<div className="balance-model"><div className="balance-side"><div>{Array.from({length:v.c||1},(_,i)=><span className="unknown-block visual-item" key={i} style={delay(i)}>x</span>)}<span>+ {v.a}</span></div></div><strong>=</strong><div className="balance-side"><span className="balance-total">{v.b}</span></div></div>;instruction='Each x has the same unknown value. Both sides represent equal amounts.';
 }else if(v.kind==='coordinates'||v.kind==='slope'){
  const slope=v.kind==='slope',x1=slope?0:v.a,y1=slope?v.b:v.b,x2=slope?1:v.c!,y2=slope?v.a+v.b:v.d!;
  const maxX=Math.max(x2+2,y2+2,5),maxY=maxX,px=(x:number)=>135+x/maxX*190,py=(y:number)=>220-y/maxY*190;
  title=slope?'One step across. How far up?':'Two points on a grid';content=<Canvas label={`Coordinate grid with A (${x1}, ${y1}) and B (${x2}, ${y2})`}>{Array.from({length:maxX+1},(_,i)=><line key={`x${i}`} x1={px(i)} y1="30" x2={px(i)} y2="220" stroke="#dce5eb"/>)}{Array.from({length:maxY+1},(_,i)=><line key={`y${i}`} x1="135" y1={py(i)} x2="325" y2={py(i)} stroke="#dce5eb"/>)}<path d="M135 25 V220 H345" fill="none" stroke="#6b8697" strokeWidth="2"/><text x="345" y="242">x</text><text x="113" y="27">y</text><text x="120" y="238">0</text><path className="draw-line" d={`M${px(x1)} ${py(y1)} L${px(x2)} ${py(y2)}`} fill="none" stroke="#3989b6" strokeWidth="3"/><circle cx={px(x1)} cy={py(y1)} r="6" fill="#28684a"/><circle cx={px(x2)} cy={py(y2)} r="6" fill="#397caf"/><text x={px(x1)+9} y={py(y1)+20} fontSize="15">A ({x1}, {y1})</text><text x={px(x2)+7} y={py(y2)-12} fontSize="15">B ({x2}, {y2})</text></Canvas>;
 }else if(v.kind==='percent'){
  title='Percent means out of 100';content=<><div className="percent-grid" role="img" aria-label={`${v.a} of 100 equal cells shaded`}>{Array.from({length:100},(_,i)=><i key={i} className={i<v.a?'filled':''}/>)}</div><span className="whole-label">The whole grid represents {v.b} books · shaded portion {v.a}%</span></>;
 }else if(v.kind==='partition'){
  const u=180/(v.a+v.b),x=135,y=35,s=v.a*u,t=v.b*u;title='Split the square into regions';content=<Canvas label={`A square with each side split into ${v.a} and ${v.b}`}><rect x={x} y={y} width={s} height={s} fill="#bddfc6"/><rect x={x+s} y={y} width={t} height={s} fill="#bfdcf4"/><rect x={x} y={y+s} width={s} height={t} fill="#bfdcf4"/><rect x={x+s} y={y+s} width={t} height={t} fill="#ffe2a3"/><rect x={x} y={y} width="180" height="180" fill="none" stroke="#527e70" strokeWidth="2"/><text x={x+s/2} y="24" textAnchor="middle">{v.a}</text><text x={x+s+t/2} y="24" textAnchor="middle">{v.b}</text><text x="114" y={y+s/2}>{v.a}</text><text x="114" y={y+s+t/2}>{v.b}</text><text x="240" y="250" textAnchor="middle">Add the areas of all four regions</text></Canvas>;
 }else if(v.kind==='cuboid'){
  title='Length. Width. Height.';content=<Canvas label={`Cuboid with length ${v.a}, width ${v.b}, height ${v.c}. Schematic, not to scale.`}><path d="M130 95 L205 45 H350 L275 95 Z" fill="#d9f0d7" stroke="#55816c" strokeWidth="2"/><path d="M275 95 L350 45 V160 L275 210 Z" fill="#9ac8a7" stroke="#55816c" strokeWidth="2"/><path d="M130 95 H275 V210 H130 Z" fill="#bddfc6" stroke="#55816c" strokeWidth="2"/><text x="200" y="238" textAnchor="middle">{v.a} units</text><text x="365" y="118">{v.c} units</text><text x="306" y="38" textAnchor="middle">{v.b} units</text></Canvas>;instruction='A schematic cuboid, not drawn to scale. Use the three labelled dimensions.';
 }else if(v.kind==='frequency'){
  title='Every midpoint has a frequency';content=<table className="visual-table"><thead><tr><th>Class midpoint</th><th>Frequency</th></tr></thead><tbody><tr><td>{v.a}</td><td>{v.c}</td></tr><tr><td>{v.b}</td><td>{v.d}</td></tr></tbody></table>;instruction='Use each frequency as the number of times its midpoint contributes to the estimate.';
 }
 if(!content)return null;
 return <section className={`play-model model-${v.kind}`} aria-label="Visual question model"><div className="model-heading"><span><Blocks size={16}/>{title}</span><button type="button" onClick={reset} aria-label="Reset visual model and replay entrance"><RotateCcw size={15}/><span>Reset</span></button></div><div key={replay} className="model-stage">{content}</div><p className="model-instruction"><Hand size={16}/>{instruction}</p></section>;
}

export function MotionControl(){
 const [reduced,setReduced]=useState(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const read=()=>{let saved:string|null=null;try{saved=localStorage.getItem('aarambh-motion');}catch{}const low=saved?saved==='reduced':media.matches;setReduced(low);document.documentElement.dataset.motion=low?'reduced':'full';};read();media.addEventListener('change',read);return()=>media.removeEventListener('change',read);},[]);
 function toggle(){const low=!reduced;setReduced(low);document.documentElement.dataset.motion=low?'reduced':'full';try{localStorage.setItem('aarambh-motion',low?'reduced':'full');}catch{}}
 return <button className="motion-control" onClick={toggle} aria-pressed={reduced} title="Reduce decorative animation on this device">{reduced?<Pause size={15}/>:<Play size={15}/>}<span>Motion: {reduced?'low':'on'}</span></button>;
}
export function AnswerCelebration(){return <div className="answer-celebration" aria-hidden="true"><span><Sparkles size={24}/></span>{Array.from({length:12},(_,i)=><i key={i} style={{'--dx':`${Math.cos(i*Math.PI/6)*(55+i%3*15)}px`,'--dy':`${Math.sin(i*Math.PI/6)*65-20}px`,'--angle':`${i*37}deg`,'--item-delay':`${i%3*60}ms`} as CSSProperties}/>)}</div>}

const demos=[{id:'count',name:'Count together',question:'How many counters are there altogether?',model:{kind:'counters',a:4,b:3},answer:7},{id:'fractions3',name:'See a fraction',question:'What fraction of this whole is shaded?',model:{kind:'fraction',a:3,b:8},answer:3/8},{id:'area',name:'Build an area',question:'What is the area of this 6 cm by 3 cm rectangle?',model:{kind:'rectangle',a:6,b:3},answer:18}];
export function VisualPlayground(){
 const [index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[status,setStatus]=useState('');const demo=demos[index];
 return <div className="visual-playground"><div className="playground-heading"><div><span className="eyebrow">A LITTLE PLAY, A LITTLE DISCOVERY</span><h2>Try the maths with your hands.</h2><p>Three sample activities. No learner history is created here.</p></div><Sparkles size={25}/></div><div className="demo-tabs" role="group" aria-label="Choose a sample activity">{demos.map((d,i)=><button key={d.id} aria-pressed={i===index} onClick={()=>{setIndex(i);setAnswer('');setStatus('');}}>{d.name}</button>)}</div><h3>{demo.question}</h3><MathVisual key={demo.id} visual={demo.model} concept={demo.id}/><form className="demo-answer" onSubmit={e=>{e.preventDefault();const parts=answer.trim().split('/');const n=parts.length===2&&Number(parts[1])!==0?Number(parts[0])/Number(parts[1]):parts.length===1?Number(parts[0]):NaN;setStatus(answer.trim()&&Number.isFinite(n)&&n===demo.answer?'That matches. Try another way to show it!':'Take another look at the model. You can try again.');}}><label htmlFor="demo-answer">Your answer</label><Input id="demo-answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={index===1?'For example, 1/4':'Enter a number'} required/><Button type="submit">Give it a try</Button></form>{status&&<p className="demo-response" role="status"><Lightbulb size={17}/>{status}</p>}</div>;
}
