import type {Exercise} from './lesson-engine';
/** Answers stay on the server. Visuals only describe the givens. */
export function adventureExercise(id:string,index:number,seed:number,review=false):Exercise{
 const a=2+seed%5,b=1+Math.floor(seed/5)%4,c=2+Math.floor(seed/20)%4;
 let prompt='',story='',answer=0,hint='',explanation='',unit='';let visual:Exercise['visual'];
 switch(id){
 case 'bonds1':answer=10-a;prompt=`${a} + ? = 10. What is the missing part?`;story=`A ten-frame has ${a} counters. How many more will fill it?`;hint='Count the empty spaces, or count on from the filled part to ten.';explanation=`${a} + ${answer} = 10. The two parts together fill the whole frame.`;visual={kind:'tenframe',a,b:10};break;
 case 'position1':answer=a+1;prompt=`A star has ${a} dots before it. What is its position counting from the left? Enter the position number.`;story=`In a line starting on the left, ${a} stones come before a leaf. What is the leaf’s position number?`;hint='Count every position from the starting end, including the target.';explanation=`${a} positions come before it, so its position is ${a}+1 = ${answer}.`;visual={kind:'ordinal',a,b:2};break;
 case 'parity2':{const n=a*2+(seed%2);answer=n%2;prompt=`Pair up ${n} counters. How many are left without a partner?`;story=`${n} mittens are arranged in pairs. How many mittens remain unpaired?`;hint='Make groups of exactly two and look at what remains.';explanation=`${n} = 2 × ${a} + ${answer}, so ${answer} remain${answer===1?'s':''}. This number is ${answer?'odd':'even'}.`;visual={kind:'pairing',a:n,b:0};break;}
 case 'calendar2':answer=b*7+c;prompt=`How many days are in ${b} complete week${b===1?'':'s'} and ${c} more days?`;story=`You watch a plant for ${b} weeks and ${c} extra days. How many days have you watched?`;hint='One whole week has seven days. Combine the weeks before adding the extra days.';explanation=`${b} × 7 + ${c} = ${answer} days.`;unit='days';visual={kind:'weeks',a:b,b:c};break;
 case 'rounding3':{const n=a*10+seed%10;answer=Math.floor((n+5)/10)*10;prompt=`Round ${n} to the nearest ten. At halfway, choose the greater ten.`;story=`There are ${n} beads. Estimate the count to the nearest ten, rounding halfway upward.`;hint=`Compare its distances from ${a*10} and ${(a+1)*10}.`;explanation=`${n} rounds to ${answer} using the stated halfway rule.`;visual={kind:'rounding',a:n,b:a*10};break;}
 case 'mass3':answer=b*1000+c*100;prompt=`Convert ${b} kg ${c*100} g into grams.`;story=`A parcel has mass ${b} kg ${c*100} g. What is its mass in grams?`;hint='Each kilogram is 1,000 grams.';explanation=`${b} × 1000 + ${c*100} = ${answer} g.`;unit='g';break;
 case 'fraction_compare4':{const d=a+b+2;answer=(a+b)/d;prompt=`Which is greater: ${a}/${d} or ${a+b}/${d}? Enter the greater fraction.`;story=`Two equal-sized trays have ${a}/${d} and ${a+b}/${d} filled. Which fraction is greater?`;hint='The equal denominators make the parts the same size. Compare how many parts there are.';explanation=`${a+b}/${d} is greater because ${a+b} equal parts exceed ${a} of those same parts.`;visual={kind:'fraction-compare',a,b:a+b,c:d};break;}
 case 'area_composite4':answer=(a+b)*c;prompt=`Two non-overlapping rectangles measure ${a} × ${c} cm and ${b} × ${c} cm. Find their total area.`;story=`Two garden beds have lengths ${a} and ${b} m and both have width ${c} m. They do not overlap. What is their combined area in square metres?`;hint='Find each rectangular area, then add. A shared boundary has no area.';explanation=`${a} × ${c} + ${b} × ${c} = ${answer} square units.`;unit=index%3===2?'m²':'cm²';visual={kind:'composite',a,b,c};break;
 case 'decimal_compare5':{const x=a/10,y=(a*10-2)/100;answer=x;prompt=`Which is greater: ${x.toFixed(1)} or ${y.toFixed(2)}? Enter the greater decimal.`;story=`Ribbons measure ${y.toFixed(2)} m and ${x.toFixed(1)} m. Enter the longer length in metres.`;hint='Write both amounts in hundredths, then compare.';explanation=`${x.toFixed(1)} = ${x.toFixed(2)}, which is greater than ${y.toFixed(2)}.`;visual={kind:'decimal-compare',a:x,b:y};break;}
 case 'fraction_unlike5':{const d=b+2;answer=1/d+1/(2*d);prompt=`Find 1/${d} + 1/${2*d}. Enter an exact fraction or decimal.`;story=`You use 1/${d} of a ribbon and another 1/${2*d} of the same whole ribbon. What fraction is used?`;hint=`Rename 1/${d} using ${2*d} equal parts.`;explanation=`1/${d} = 2/${2*d}, so the sum is 3/${2*d}.`;visual={kind:'unlike-fractions',a:d,b:2*d};break;}
 case 'order_integer6':answer=-(a+b);prompt=`Find the least integer in ${b}, −${a+b}, 0, −${a}.`;story=`Four temperatures are ${b}°C, −${a+b}°C, 0°C and −${a}°C. Enter the lowest.`;hint='The least number lies furthest left on a number line.';explanation=`−${a+b} < −${a} < 0 < ${b}, so the least is −${a+b}.`;visual={kind:'integer-cards',a:0,b:0,values:[b,-(a+b),0,-a]};break;
 case 'unit_rate6':answer=(a+1)*c;prompt=`${a} identical items cost ₹${a*c}. What do ${a+1} cost at the same per-item price?`;story=`${a} notebooks cost ₹${a*c}, with no discounts. How many rupees do ${a+1} notebooks cost?`;hint=`First find the price of one item by dividing ${a*c} by ${a}.`;explanation=`One costs ₹${c}, so ${a+1} cost ₹${answer}.`;unit='rupees';break;
 case 'percent_change7':{const total=a*100,rate=b*10;answer=total*(100-rate)/100;prompt=`An item priced ₹${total} has a ${rate}% discount. Find the sale price.`;story=`A shop reduces a ₹${total} price by ${rate}%. How much is paid after the discount?`;hint='Find the discount on the original price, then subtract it.';explanation=`Discount = ${rate}/100 × ${total} = ₹${total-answer}. Sale price = ₹${answer}.`;unit='rupees';visual={kind:'percent',a:rate,b:total};break;}
 case 'speed7':answer=a*5*b;prompt=`At a constant ${a*5} km/h for ${b} hours, how many kilometres are travelled?`;story=`A model vehicle moves at a constant ${a*5} km/h without stopping for ${b} hours. What distance does it cover?`;hint='Each hour adds the same distance. Multiply speed by time.';explanation=`${a*5} km/h × ${b} h = ${answer} km.`;unit='km';break;
 case 'graph_table8':answer=a*c+b;prompt=`The rule is y = ${a}x + ${b}. Find y when x = ${c}.`;story=`A machine multiplies its input by ${a} then adds ${b}. What output comes from ${c}?`;hint='Multiply the input first, then add the fixed amount.';explanation=`y = ${a} × ${c} + ${b} = ${answer}.`;visual={kind:'rule-table',a,b,c};break;
 case 'growth8':{const total=a*100,rate=b*10;answer=total*(100+rate)**2/10000;prompt=`${total} increases by ${rate}%, then increases by ${rate}% again. Find the final amount.`;story=`A model collection of ${total} units grows by ${rate}% in each of two rounds. Each round uses the new total. What is the final amount?`;hint=`Multiply the starting amount by ${1+rate/100} twice.`;explanation=`${total} × ${(1+rate/100).toFixed(1)}² = ${answer}. The second increase uses the new base.`;break;}
 case 'midpoint9':answer=a+b;prompt=`Find the x-coordinate of the midpoint between (${a}, ${c}) and (${a+2*b}, ${c+2*b}).`;story=`Two map markers are at (${a}, ${c}) and (${a+2*b}, ${c+2*b}). What is the x-coordinate halfway along their straight segment?`;hint='Average the two x-coordinates. Keep the y calculation separate.';explanation=`The midpoint is (${a+b}, ${c+b}), because each coordinate is the mean of the corresponding endpoint coordinates.`;visual={kind:'coordinates',a,b:c,c:a+2*b,d:c+2*b};break;
 case 'intercept9':answer=b;prompt=`For y = ${a}x + ${b}, find the y-intercept.`;story=`A linear model y = ${a}x + ${b} describes a fee. What is y when x is zero?`;hint='At the y-axis, x equals zero. Substitute zero for x.';explanation=`y = ${a} × 0 + ${b} = ${b}. The crossing is (0, ${b}).`;visual={kind:'slope',a,b};break;
 case 'similarity10':answer=(a+1)*b;prompt=`Two triangles are similar. A side of ${a} cm corresponds to ${a*b} cm. A second side of the smaller triangle is ${a+1} cm. Find its corresponding larger side.`;story=prompt;hint='Find the ratio of corresponding sides, then use the same multiplier.';explanation=`The scale factor is ${a*b}/${a} = ${b}. The required side is ${a+1} × ${b} = ${answer} cm.`;unit='cm';visual={kind:'similarity',a,b,c:a+1};break;
 case 'sector10':{const radius=7*b,angle=seed%2?90:180;answer=angle/360*22/7*radius*radius;prompt=`Find the area of a ${angle}° sector with radius ${radius} cm. Use π = 22/7.`;story=`A fan-shaped garden is a ${angle}° sector of a circle of radius ${radius} m. Use π = 22/7 to find its area in square metres.`;hint='Take angle/360 of the whole-circle area πr².';explanation=`Area = ${angle}/360 × 22/7 × ${radius}² = ${answer} square units.`;unit=index%3===2?'m²':'cm²';visual={kind:'sector',a:radius,b:angle};break;}
 default:throw new Error(`No practice generator for ${id}`);
 }
 const format=index%3===2?'story':visual&&index%3===0?'visual':'numbers';
 return {concept:id,format,prompt:format==='story'?story:prompt,answer,hint,explanation,unit,visual:format==='visual'?visual:undefined,review};
}
