import {teachingRecords,type TeachingRecord} from './curriculum-content';
export type Concept=TeachingRecord&{description:string;prerequisite:string;curriculumStatus:string;sourceId:string;sourceLocator:string};
const locators:Record<string,string>={midpoint9:'Unit III: Coordinate Geometry, p. 7',intercept9:'Unit II: Introduction to Polynomials, p. 5',similarity10:'Unit IV: Triangles, p. 5',sector10:'Unit VI: Areas Related to Circles, p. 7',real9:'Unit I: Number System, p. 4',polynomial9:'Unit II: Introduction to Polynomials, p. 5',slope:'Unit II: Introduction to Polynomials / Linear Equations, pp. 5–6',sequence9:'Unit II: Sequences and Progressions, p. 5',coordinates9:'Unit III: Coordinate Geometry, p. 7',triangle:'Prerequisite support for coordinate distance; not a standalone syllabus chapter',angles9:'Unit IV: Lines and Angles, pp. 7–8',statistics9:'Unit VI: Statistics',real10:'Unit I: Real Numbers, p. 3',quadratic:'Unit II: Quadratic Equations, p. 4',simultaneous10:'Unit II: Pair of Linear Equations, pp. 3–4',ap10:'Unit II: Arithmetic Progressions, p. 4',trig10:'Unit V: Trigonometry, p. 6',circle10:'Unit IV: Circles, p. 6',probability:'Unit VII: Probability',statistics10:'Unit VII: Statistics'};
const adventureIds=new Set(['bonds1','position1','parity2','calendar2','rounding3','mass3','fraction_compare4','area_composite4','decimal_compare5','fraction_unlike5','order_integer6','unit_rate6','percent_change7','speed7','graph_table8','growth8','midpoint9','intercept9','similarity10','sector10']);
export const concepts:Concept[]=[...teachingRecords].sort((a,b)=>a.grade-b.grade || Number(adventureIds.has(a.id))-Number(adventureIds.has(b.id))).map(c=>({...c,description:c.goal,prerequisite:c.prerequisites.map(id=>teachingRecords.find(p=>p.id===id)?.title||id).join(' · ')||'No earlier concept is assumed',curriculumStatus:c.grade<9?'Provisional grade placement':c.id==='triangle'?'Prerequisite support':'Topic matched to 2026–27 syllabus',sourceId:c.grade===9?'S08':c.grade===10?'S09':'S01',sourceLocator:locators[c.id]||'NCERT textbook portal. Exact current-edition chapter alignment is pending.'}));
export const curriculumSources={
 S01:{title:'NCERT textbook portal',url:'https://ncert.nic.in/textbook.php',checked:'2026-10-06',note:'Portal located. These Classes 1–8 assignments are an original proposed sequence; current-edition chapter placement is not verified.'},
 S08:{title:'CBSE Mathematics, Class IX, 2026–27',url:'https://cbseacademic.nic.in/web_material/CurriculumMain27/SecPart1/Maths_SecP1IX_2026-27.pdf',checked:'2026-10-06',note:'Official syllabus text checked for topic correspondence. This does not imply complete chapter coverage or educator approval.'},
 S09:{title:'CBSE Mathematics, Class X, 2026–27',url:'https://cbseacademic.nic.in/web_material/CurriculumMain27/SecPart1/Maths_SecP1X_2026-27.pdf',checked:'2026-10-06',note:'Official syllabus text checked for topic correspondence. All explanations, examples and practice here are original drafts.'},
};
export const gradeGuides:Record<number,{focus:string;aim:string;next:string}>={
1:{focus:'Concrete quantities, simple shapes and comparison',aim:'Build meaning through touching, grouping, speaking and noticing. Introduce notation after an action makes sense.',next:'Broaden number ranges and contextual problems; validate language and activities with a foundational-stage educator.'},
2:{focus:'Place value, exchanges and everyday measurements',aim:'Connect bundles of ten with addition and subtraction. Use real clock, money and measurement contexts.',next:'Add more addition and subtraction structures, calendar reading and shapes; check the current textbook sequence.'},
3:{focus:'Equal groups, early fractions and larger quantities',aim:'Connect multiplication and division while distinguishing a whole, its equal parts and its units.',next:'Broaden tables, spatial tasks and measurement activities. Confirm when each topic is introduced in the selected school.'},
4:{focus:'Flexible calculation, equivalence and measurement',aim:'Explain calculations through partitioning and use clear units for boundaries, capacities and data.',next:'Add richer division, multi-step word problems and construction activities. These ten guides are not a full year plan.'},
5:{focus:'Decimal place value, fractions and spatial reasoning',aim:'Link whole-number reasoning to fractional units and connect arrays, areas and volumes.',next:'Broaden fraction operations and open investigations after checking the selected edition.'},
6:{focus:'Number relationships and the first abstractions',aim:'Connect concrete models with signed numbers, fractional quantities, variables and statistical summaries.',next:'The new textbook sequence may place these topics differently. Edition alignment, constructions and further pattern work remain.'},
7:{focus:'Equations, proportional reasoning and geometry',aim:'Explain why an operation is appropriate, state assumptions and use counterexamples when needed.',next:'Add further triangle properties, constructions, rational arithmetic and data investigations; verify grade placement.'},
8:{focus:'Algebraic structure, powers and measurement models',aim:'Use inverse operations, distributivity and proportional models with their necessary conditions.',next:'Add quadrilaterals, further mensuration, graphs and proof activities; validate the current edition’s scope.'},
9:{focus:'Algebra, coordinates and mathematical justification',aim:'Connect equations, patterns and geometry. Explain the conditions under which a relationship is valid.',next:'Selected topics only. Euclidean axioms, congruence, quadrilaterals, circles, mensuration, fuller statistics and probability remain to be developed.'},
10:{focus:'Equations, trigonometry and interpretation of data',aim:'Move between representations, verify solutions and distinguish exact results from estimates.',next:'Selected topics only. Polynomial zero relationships, similarity proofs, section formula, trigonometric identities, heights and distances, segments, solids and fuller grouped-data work remain.'},
};
export type Attempt={id:string;learner:string;concept:string;format:string;correct:number;assisted:number;review:number;response:string;question:string;created:string;signature?:string;interaction?:string;reflection?:string};
export function evidence(attempts:Attempt[],concept:string) {
 const a=attempts.filter(x=>x.concept===concept);
 const independent=[...new Map(a.filter(x=>x.correct&&!x.assisted&&x.interaction!=='choice').map(x=>[x.signature||x.question,x])).values()];
 const varied=new Set(independent.map(x=>x.format));
 return {total:a.length,independent:independent.length,formats:varied.size,retained:a.some(x=>x.correct&&!x.assisted&&x.interaction!=='choice'&&x.review),stage:a.some(x=>x.correct&&!x.assisted&&x.interaction!=='choice'&&x.review)?'Revisited independently':varied.size>=2?'Independent examples':a.length?'Exploring':'A fresh start'};
}
