import {adventureExercise} from './adventure-lessons';
import type {Exercise} from './lesson-engine';
import {questionVisual} from './question-visuals';
/** Server-only original practice generators; each item has an explicit answer and explanation. */
export function extraExercise(id:string,index:number,seed:number,review=false):Exercise{
 const a=2+seed%5,b=1+Math.floor(seed/5)%4,c=2+Math.floor(seed/20)%4;
 let prompt='',story='',answer=0,hint='',explanation='',unit='';let visual:Exercise['visual'];
 switch(id){
 case 'count': answer=a+b;prompt=`What number comes immediately after ${a+b-1}?`;story=`You counted ${a+b-1} blocks, then counted one more. How many blocks in all?`;hint='Touch each counter once. The last number you say is the total.';explanation=`The group contains ${answer} counters, regardless of their arrangement.`;visual={kind:'counters',a:a+b,b:0};break;
 case 'compare':answer=a+b;prompt=`Which number is larger: ${a} or ${a+b}? Enter the larger number.`;story=`One tray has ${a} counters and another has ${a+b}. How many are in the tray with more?`;hint='Match objects one to one and see which group has some left.';explanation=`${a+b} is larger than ${a}, by ${b}.`;break;
 case 'zero':answer=0;prompt=`What is ${a+b} − ${a+b}?`;story=`All ${a+b} pebbles are removed from a box holding ${a+b}. How many remain?`;hint='An empty collection has a number too.';explanation='Removing every object leaves zero objects.';break;
 case 'shapes1':answer=seed%2?4:3;prompt=`How many straight sides does a ${seed%2?'rectangle':'triangle'} have?`;story=`Trace a ${seed%2?'rectangular':'triangular'} card. How many straight sides do you trace?`;hint='Count each straight edge of the boundary once.';explanation=`A ${seed%2?'rectangle has four':'triangle has three'} straight sides.`;break;
 case 'pattern1':answer=seed%2?a:b;prompt=seed%2?`Complete the repeating pattern: ${a}, ${a+b}, ${a}, ${a+b}, __.`:`Complete the repeating pattern: ${a+b}, ${b}, ${a+b}, ${b}, ${a+b}, __.`;story=prompt+' Imagine the numbers on alternating coloured cards.';hint='Identify the pair that repeats, then find the next position.';explanation=`Repeating the same two-number unit puts ${answer} in the missing position.`;break;
 case 'length1':answer=a+b;prompt=`Two strips measure ${a} and ${a+b} identical blocks. Enter the longer length in blocks.`;story=`A bookmark is ${a} blocks long and a ribbon is ${a+b} of the same blocks long. How long is the longer object?`;hint='The unit blocks must all have the same length.';explanation=`${a+b} identical blocks cover a longer distance than ${a}.`;unit='blocks';break;
 case 'regroup2':{const total=a*10+2,sub=b+3;answer=total-sub;prompt=`What is ${total} − ${sub}?`;story=`A tray holds ${total} beads. You remove ${sub}. How many remain?`;hint='Exchange one ten for ten ones, then remove the required ones.';explanation=`${total} becomes ${a-1} tens and 12 ones. Removing ${sub} leaves ${answer}.`;break;}
 case 'skip2':answer=(a+3)*b;prompt=`Continue: ${a*b}, ${(a+1)*b}, ${(a+2)*b}, __.`;story=`A counter moves forward ${b} each time: ${a*b}, ${(a+1)*b}, ${(a+2)*b}. Where is the next stop?`;hint=`Keep adding the same step of ${b}.`;explanation=`${(a+2)*b} + ${b} = ${answer}.`;break;
 case 'money2':answer=20-a-b;prompt=`What change comes from ₹20 after spending ₹${a+b}?`;story=`You pay ₹20 for a notebook costing ₹${a+b}. How many rupees should come back?`;hint='Find the gap between the price and the amount paid.';explanation=`20 − ${a+b} = ${answer}.`;unit='rupees';break;
 case 'time2':answer=b;prompt=`How many hours pass from ${a}:00 to ${a+b}:00 on the same morning?`;story=`A morning workshop runs from ${a}:00 to ${a+b}:00. How many hours does it last?`;hint='Count the one-hour intervals between the start and finish.';explanation=`${a+b} − ${a} = ${b} hours.`;unit='hours';break;
 case 'measure2':answer=b+c;prompt=`A strip starts at ${a} cm on a ruler and ends at ${a+b+c} cm. Find its length.`;story=`The zero mark is hidden, so you measure a ribbon from ${a} cm to ${a+b+c} cm. How long is it?`;hint='The length is the difference between the end and start readings.';explanation=`${a+b+c} − ${a} = ${answer} cm.`;unit='cm';break;
 case 'data2':answer=a+b;prompt=`A count table has ${a} circles and ${b} squares. How many shapes in total?`;story=`A class sorts ${a} round buttons and ${b} square buttons. What is the total count?`;hint='Add the two category counts, with each item counted once.';explanation=`${a} + ${b} = ${answer}.`;break;
 case 'hundreds3':answer=a*100;prompt=`What is the value of the hundreds digit in ${a*100+b*10+c}?`;story=`The number ${a*100+b*10+c} is written in a place-value table. What amount does its hundreds digit represent?`;hint='The hundreds digit counts groups of one hundred.';explanation=`${a} hundreds = ${a} × 100 = ${answer}.`;break;
 case 'remainders3':{const divisor=b+2,rem=1+seed%(divisor-1),n=a*divisor+rem;answer=rem;prompt=`What is the remainder when ${n} is divided by ${divisor}?`;story=`Pack ${n} pencils into boxes of ${divisor}. How many are left outside the full boxes?`;hint='Make as many full groups as possible; the leftover is smaller than the group size.';explanation=`${n} = ${a} × ${divisor} + ${rem}, so the remainder is ${rem}.`;break;}
 case 'fractions3':answer=1/(b+2);prompt=`One of ${b+2} equal parts is shaded. What fraction of the whole is shaded?`;story=`A strip is divided into ${b+2} equal sections and one is coloured. Enter the coloured fraction, such as 1/4.`;hint='One part is selected out of the total number of equal parts.';explanation=`The fraction is 1/${b+2}.`;break;
 case 'clock3':{const start=35+5*b,end=5*c;answer=60-start+end;prompt=`How many minutes pass from 2:${start} to 3:${String(end).padStart(2,'0')}?`;story=`A reading activity starts at 2:${start} and ends at 3:${String(end).padStart(2,'0')}. Find its duration in minutes.`;hint='Count to 3:00 first, then add the remaining minutes.';explanation=`${60-start} minutes to the hour + ${end} minutes after it = ${answer}.`;unit='minutes';break;}
 case 'length3':answer=a*100+b*10+c;prompt=`Convert ${a} m ${b*10+c} cm to centimetres.`;story=`A ribbon is ${a} metres and ${b*10+c} centimetres long. Give its length entirely in centimetres.`;hint='Each metre contains one hundred centimetres.';explanation=`${a} × 100 + ${b*10+c} = ${answer} cm.`;unit='cm';break;
 case 'shapes3':answer=4*a;prompt=`A square has side length ${a} cm. What is the total length of its four sides?`;story=`Trim goes around all four sides of a square tile, each ${a} cm long. How much trim is needed?`;hint='A square has four equal sides.';explanation=`4 × ${a} = ${answer} cm.`;unit='cm';break;
 case 'multiply4':answer=(a*10+b)*c;prompt=`Calculate ${a*10+b} × ${c}.`;story=`Each of ${c} boxes contains ${a*10+b} pencils. How many pencils altogether?`;hint=`Partition ${a*10+b} into ${a*10} and ${b}, multiply each part, then add.`;explanation=`${a*10} × ${c} + ${b} × ${c} = ${a*10*c} + ${b*c} = ${answer}.`;break;
 case 'divide4':answer=a*10+b;prompt=`Calculate ${(a*10+b)*c} ÷ ${c}.`;story=`Share ${(a*10+b)*c} cards equally among ${c} teams. How many per team?`;hint='Split the total into convenient multiples of the divisor.';explanation=`${a*10*c} ÷ ${c} = ${a*10}, and ${b*c} ÷ ${c} = ${b}. Total: ${answer}.`;break;
 case 'factors4':answer=seed%2?b+2:a;prompt=seed%2?`Complete the factor pair of ${(a+1)*(b+2)}: ${a+1} × ?.`:`Complete the factor pair of ${a*(b+1)}: ? × ${b+1}.`;story=prompt+' This describes a rectangular arrangement of counters.';hint='Use the inverse relationship between multiplication and division.';explanation=`The missing factor is ${answer}; multiplying the two factors reconstructs the original number.`;break;
 case 'symmetry4':answer=seed%2?2:4;prompt=`How many lines of symmetry does a ${seed%2?'non-square rectangle':'square'} have?`;story=`Fold a paper ${seed%2?'rectangle whose adjacent sides have different lengths':'square'} so the halves match exactly. How many different symmetry lines are there?`;hint='Try folds through opposite side midpoints and then check the diagonals.';explanation=seed%2?'A non-square rectangle has two lines of symmetry; its diagonals do not create matching halves.':'A square has four lines of symmetry: two diagonals and two midpoint lines.';break;
 case 'measurement4':answer=a*1000+b*100;prompt=`Convert ${a} L ${b*100} mL to millilitres.`;story=`A jug contains ${a} litres and ${b*100} millilitres. How many millilitres is that?`;hint='One litre is one thousand millilitres.';explanation=`${a} × 1,000 + ${b*100} = ${answer} mL.`;unit='mL';break;
 case 'data4':answer=a*(b+1);prompt=`A pictograph shows ${a} symbols. Its key says each symbol represents ${b+1} books. How many books?`;story=`The library’s chart has ${a} stars, each worth ${b+1} borrowed books. Find the total books.`;hint='Multiply the number of symbols by the quantity represented by each.';explanation=`${a} × ${b+1} = ${answer}.`;break;
 case 'decimal_place5':answer=b/100;prompt=`What is the value of the hundredths digit in ${a}.${c}${b}?`;story=`A measurement reads ${a}.${c}${b} metres. What amount is represented by the digit ${b} in the hundredths place?`;hint='The second digit after the decimal point counts hundredths.';explanation=`${b} hundredths is ${b}/100 = ${(b/100).toFixed(2)}.`;break;
 case 'fraction_add5':answer=(a+b)/(a+b+c);prompt=`Find ${a}/${a+b+c} + ${b}/${a+b+c}. Enter a fraction or an exact decimal.`;story=`Two portions of the same whole are ${a}/${a+b+c} and ${b}/${a+b+c}. What fraction do they make together?`;hint='Both denominators name the same-sized parts. Add only the counts of those parts.';explanation=`(${a} + ${b})/${a+b+c} = ${a+b}/${a+b+c}. Equivalent fractions are accepted.`;break;
 case 'volume5':answer=a*b*c;prompt=`A cuboid is ${a} units long, ${b} units wide and ${c} units high. Find its volume.`;story=`A crate holds ${c} layers of cubes with ${a*b} unit cubes per layer. How many unit cubes fit?`;hint='Find the count in one complete layer, then multiply by the number of layers.';explanation=`${a} × ${b} × ${c} = ${answer} cubic units.`;unit='cubic units';break;
 case 'angles5':answer=seed%2?180:90;prompt=`How many degrees are in a ${seed%2?'half':'quarter'} turn?`;story=`You turn through ${seed%2?'half':'a quarter of'} a full circle. What angle have you turned through?`;hint='A full turn has 360 degrees.';explanation=seed%2?'360 ÷ 2 = 180°.':'360 ÷ 4 = 90°.';unit='degrees';break;
 case 'patterns5':answer=a+4*b;prompt=`Find the fifth term: ${a}, ${a+b}, ${a+2*b}, …`;story=`A design begins with ${a} tiles and gains ${b} at each new stage. How many tiles are in stage five?`;hint='The fifth term is four equal steps after the first.';explanation=`${a} + 4 × ${b} = ${answer}.`;break;
 case 'data5':answer=b*c;prompt=`A table records ${a*10} on Monday and ${a*10+b*c} on Tuesday. How many more on Tuesday?`;story=`Visitors number ${a*10} on Monday and ${a*10+b*c} on Tuesday. Find the increase.`;hint='A comparison asking “how many more” needs the difference.';explanation=`${a*10+b*c} − ${a*10} = ${answer}.`;break;
 case 'prime6':answer=a;prompt=`Find the highest common factor of ${a*b} and ${a*(b+1)}.`;story=`Two collections contain ${a*b} and ${a*(b+1)} items. What is the largest equal packet size that divides both collections exactly?`;hint='List the positive factors of each quantity and choose the greatest shared one.';explanation=`The HCF is ${a}. The other factors ${b} and ${b+1} are consecutive integers and share no factor greater than one.`;break;
 case 'fraction_calc6':answer=1/2+1/(2*c);prompt=`Calculate 1/2 + 1/${2*c}. Enter a fraction or an exact decimal.`;story=`Join a half-metre strip with a 1/${2*c}-metre strip. What is the total length in metres?`;hint=`Use ${2*c} as a common denominator.`;explanation=`1/2 = ${c}/${2*c}. The sum is ${c+1}/${2*c}.`;break;
 case 'angle6':answer=180-(a*10+b*5);prompt=`Two adjacent angles form a straight line. One is ${a*10+b*5}°. Find the other.`;story=`A straight turn is divided into ${a*10+b*5}° and a missing angle. Find the missing angle.`;hint='The specified straight-line pair adds to 180 degrees.';explanation=`180 − ${a*10+b*5} = ${answer}°.`;unit='degrees';break;
 case 'algebra6':answer=a*c+b;prompt=`Evaluate ${a}n + ${b} when n = ${c}.`;story=`You have ${a} packs with ${c} pencils each and ${b} loose pencils. How many pencils?`;hint='Replace the letter with its value, multiply, then add.';explanation=`${a} × ${c} + ${b} = ${answer}.`;break;
 case 'mean6':answer=a+b;prompt=`Find the mean of ${a}, ${a+b}, ${a+2*b}.`;story=`Three daily counts are ${a}, ${a+b} and ${a+2*b}. What is their arithmetic mean?`;hint='Add every value, then divide by the number of values.';explanation=`(${a} + ${a+b} + ${a+2*b}) ÷ 3 = ${answer}.`;break;
 case 'symmetry6':answer=seed%2?2:4;prompt=`What is the order of rotational symmetry of a ${seed%2?'non-square rectangle':'square'}?`;story=`A paper ${seed%2?'non-square rectangle':'square'} rotates through one full turn. How many times does it match its starting outline, counting the final full turn?`;hint='Count the equal turns that make the shape coincide with its original outline.';explanation=seed%2?'It matches after 180° and 360°, giving order 2.':'It matches after 90°, 180°, 270° and 360°, giving order 4.';break;
 case 'rational7':answer=-1/2+b/(2*c);prompt=`Calculate −1/2 + ${b}/${2*c}. Enter a fraction or an exact decimal.`;story=`Starting at −1/2 on a number line, move right ${b}/${2*c}. Where do you finish?`;hint='Use a common denominator and preserve the negative sign.';explanation=`−1/2 = −${c}/${2*c}. The result is ${b-c}/${2*c}.`;break;
 case 'triangle_angle7':answer=180-a*10-b*10;prompt=`Two interior angles of a triangle are ${a*10}° and ${b*10}°. Find the third.`;story=`A triangular sign has two inside angles of ${a*10}° and ${b*10}°. What is the remaining inside angle?`;hint='All three interior angles together make 180 degrees.';explanation=`180 − ${a*10} − ${b*10} = ${answer}°.`;unit='degrees';break;
 case 'circle7':answer=44*b;prompt=`Find the circumference of a circle of radius ${7*b} cm. Use π = 22/7.`;story=`A circular mat has radius ${7*b} cm. What length of trim goes around it, using π = 22/7?`;hint='Circumference is 2 × π × radius.';explanation=`2 × (22/7) × ${7*b} = ${answer} cm.`;unit='cm';break;
 case 'exponent7':answer=a**3;prompt=`Evaluate ${a}³.`;story=`A cube contains ${a} rows of ${a} cubes in each of ${a} layers. How many small cubes?`;hint='The exponent three means three equal factors, not multiplication by three.';explanation=`${a} × ${a} × ${a} = ${answer}.`;break;
 case 'probability7':answer=1/2;prompt=seed%2?'What is P(odd) for a fair six-sided die?':'What is P(even) for a fair six-sided die?';story=prompt+' Enter a fraction or an exact decimal.';hint='List favourable outcomes and all six equally likely outcomes.';explanation='There are three favourable outcomes out of six. Probability = 3/6 = 1/2.';break;
 case 'interest7':answer=a*100*b*c/100;prompt=`Find simple interest on ₹${a*100} at ${b}% per year for ${c} years.`;story=`In a hypothetical simple-interest exercise, ₹${a*100} earns ${b}% each year for ${c} years. Find interest only, in rupees.`;hint='Use principal × annual rate × years ÷ 100.';explanation=`${a*100} × ${b} × ${c} ÷ 100 = ₹${answer}.`;unit='rupees';break;
 case 'square_root8':answer=a+b;prompt=`Find √${(a+b)**2}.`;story=`A square has area ${(a+b)**2} cm². Find its non-negative side length.`;hint='Find the non-negative number which squares to the area.';explanation=`${a+b} × ${a+b} = ${(a+b)**2}, so the principal square root is ${answer}.`;break;
 case 'cube8':answer=seed%2?-a:a;prompt=`Find the real cube root of ${answer**3}.`;story=`A number multiplied by itself three times gives ${answer**3}. What is that number?`;hint='The sign of a real cube root matches the sign of its cube.';explanation=`(${answer}) × (${answer}) × (${answer}) = ${answer**3}.`;break;
 case 'identity8':answer=(10+a)**2;prompt=`Evaluate (10 + ${a})² using the square-of-a-sum identity.`;story=`A square’s side grows from 10 to ${10+a} units. Find the new area using a partition into four regions.`;hint='Use 10² + 2 × 10 × the added length + the added length squared.';explanation=`100 + ${20*a} + ${a*a} = ${answer}.`;break;
 case 'proportion8':answer=a;prompt=`${b} identical taps fill a tank in ${2*a} hours. How many hours do ${2*b} such taps take at unchanged flow rates?`;story=`You double the number of identical independent taps from ${b} to ${2*b} for the same tank. The old filling time was ${2*a} hours. Find the new time.`;hint='The fixed volume means doubling the total flow rate halves the time.';explanation=`${2*a} ÷ 2 = ${answer} hours, under the stated equal-flow assumptions.`;unit='hours';break;
 case 'volume8':answer=154*b*b*c;prompt=`Find the volume of a cylinder with radius ${7*b} cm and height ${c} cm. Use π = 22/7.`;story=`A cylindrical container has internal radius ${7*b} cm and height ${c} cm. Calculate its volume using π = 22/7.`;hint='Calculate π × radius² × perpendicular height.';explanation=`(22/7) × ${7*b}² × ${c} = ${answer} cm³.`;unit='cm³';break;
 case 'factor8':answer=b;prompt=`Complete the factorisation: ${a*b}x + ${a*c} = ${a}(?x + ${c}). Enter the missing coefficient.`;story=`${a} identical bundles together contain ${a*b}x + ${a*c}. Each bundle is ?x + ${c}. Find the missing coefficient.`;hint='Divide the coefficient of x by the common factor outside the bracket.';explanation=`${a*b} ÷ ${a} = ${answer}. Expanding ${a}(${b}x + ${c}) recovers both original terms.`;break;
 case 'real9':answer=a+b;prompt=`Evaluate √${(a+b)**2} and enter the exact value.`;story=`A square has area ${(a+b)**2} square units. Find its exact positive side length.`;hint='A perfect-square radicand has a whole-number principal square root.';explanation=`√${(a+b)**2} = ${answer}, which is rational because it equals ${answer}/1.`;break;
 case 'polynomial9':answer=b+1;prompt=`Find the degree of ${a}x^${b+1} + ${c}x + 1.`;story=`A polynomial model is ${a}x^${b+1} + ${c}x + 1. What is the largest exponent with a non-zero coefficient?`;hint='Inspect powers in separate terms; do not add them.';explanation=`The highest non-zero power is ${b+1}, so the degree is ${answer}.`;break;
 case 'sequence9':answer=a*b**4;prompt=`A geometric progression starts at ${a} and has common ratio ${b}. Find its fifth term.`;story=`A mathematical pattern starts at ${a} and multiplies by ${b} at each new position. Find position five.`;hint='The fifth position follows four multiplications by the ratio.';explanation=`${a} × ${b}⁴ = ${answer}.`;break;
 case 'coordinates9':answer=5*b;prompt=`Find the distance between (${a}, ${c}) and (${a+3*b}, ${c+4*b}).`;story=`Two grid-map points are (${a}, ${c}) and (${a+3*b}, ${c+4*b}). Find their straight-line distance in grid units.`;hint='Use the horizontal and vertical differences as perpendicular legs.';explanation=`√(${3*b}² + ${4*b}²) = ${5*b}.`;unit='units';break;
 case 'angles9':answer=a*10+b;prompt=`Parallel lines are cut by a transversal. One angle is ${a*10+b}°. Find its corresponding angle.`;story=`In a drawing with two marked parallel lines, one corresponding angle is ${a*10+b}°. What is the matching angle?`;hint='For parallel lines, corresponding angles are equal.';explanation=`The corresponding angle is also ${answer}°, because the lines are parallel.`;unit='degrees';break;
 case 'statistics9':answer=a+b;prompt=`Find the median of ${a+2*b}, ${a}, ${a+b}, ${a+4*b}, ${a+3*b}.`;story=`Five recorded counts are ${a+2*b}, ${a}, ${a+b}, ${a+4*b}, ${a+3*b}. Find the median after ordering them.`;answer=a+2*b;hint='Sort all five values, then select the third.';explanation=`Ordered values are ${a}, ${a+b}, ${a+2*b}, ${a+3*b}, ${a+4*b}. The middle is ${answer}.`;break;
 case 'real10':answer=a*b*(b+1);prompt=`Find the least common multiple of ${a*b} and ${a*(b+1)}.`;story=`Two mathematical cycles repeat every ${a*b} and ${a*(b+1)} units. After how many units do they next coincide?`;hint='Use prime factors, or divide the product by the highest common factor.';explanation=`Their HCF is ${a}. LCM = (${a*b} × ${a*(b+1)})/${a} = ${answer}.`;break;
 case 'simultaneous10':answer=a;prompt=`Solve x + y = ${a+b}, x − y = ${a-b}. Enter the value of x.`;story=`Two quantities have sum ${a+b} and difference ${a-b}, in the stated order x minus y. Find x.`;hint='Add the two equations to eliminate y.';explanation=`2x = ${2*a}, so x = ${a}; then y = ${b}. Both equations are satisfied.`;break;
 case 'ap10':answer=a+9*b;prompt=`An arithmetic progression has first term ${a} and common difference ${b}. Find its tenth term.`;story=`A seating pattern starts with ${a} seats and adds ${b} at each row. How many in row ten?`;hint='The tenth term is nine increments after the first.';explanation=`a₁₀ = ${a} + 9 × ${b} = ${answer}.`;break;
 case 'trig10':answer=3/5;prompt=`A right triangle has shorter sides ${3*b}, ${4*b} and hypotenuse ${5*b}. Find the sine of the angle opposite ${3*b}.`;story=`In a right-triangle model, the chosen angle faces a side of ${3*b} units, and the hypotenuse is ${5*b}. Find sin θ as a fraction or exact decimal.`;hint='Sine is the opposite side divided by the hypotenuse.';explanation=`sin θ = ${3*b}/${5*b} = 3/5 = 0.6.`;break;
 case 'circle10':answer=seed%2?90:a+b;prompt=seed%2?'A tangent touches a circle at T. What is the angle between the tangent and radius OT?':`Two tangent segments from the same external point touch a circle. One is ${a+b} cm. How long is the other?`;story=prompt;hint=seed%2?'At the contact point, the radius and tangent are perpendicular.':'The two tangent segments from one external point have equal lengths.';explanation=seed%2?'The radius and tangent form a right angle of 90°.':`The other tangent segment also has length ${a+b} cm.`;break;
 case 'statistics10':answer=(a*2+(a+10)*b)/(2+b);prompt=`Class midpoints are ${a} and ${a+10}, with frequencies 2 and ${b}. Find the grouped-mean estimate. Enter an exact fraction or decimal.`;story=`A grouped table represents two intervals by midpoints ${a} and ${a+10}. Their frequencies are 2 and ${b}. Calculate the estimated mean.`;hint='Multiply each midpoint by its frequency, add, and divide by total frequency.';explanation=`Estimated mean = (${a} × 2 + ${a+10} × ${b})/(2 + ${b}) = ${a*2+(a+10)*b}/${2+b}.`;break;
 default:return adventureExercise(id,index,seed,review);
 }
 visual=visual||questionVisual(id,seed);
 const format=index%3===2?'story':visual&&index%3===0?'visual':'numbers';
 return {concept:id,format,prompt:format==='visual'&&id==='count'?'Count the counters. How many are there?':format==='story'?story:prompt,answer,hint,explanation,unit,visual:format==='visual'?visual:undefined,review};
}
